### ISSUE TITLE
Support for APKMirror .apkm files

### ISSUE THREAD

**Issue by sanatsathaye** [Aefyr/SAI#100]
APKMirror is [now allowing app bundles](https://twitter.com/ArtemR/status/1241436033801048064), however they are in proprietary .apkm format and can only be installed via the [official installer](https://play.google.com/store/apps/details?id=com.apkmirror.helper.prod). It doesn't seem to be a regular ZIP file. Would be great if SAI would be able to support it somehow.

**Comment by Aefyr** [comment]
Their installer is a joke, ads everywhere (having to watch a 30sec ad to install an app lol) and a 3 dollar/month subscription to remove it, though I agree, some features such as selecting what split parts to install are quite nice, I wanna try make a new filepicker that supports that for SAI.

Anyway their .apkm format seems to be an encrypted ZIP file, I could try reverse engineering their app, but that's a bit illegal, plus I don't wanna support their DRM thing. The best solution would probably try to make them use .apks somehow, but they probably won't.
So, I'm not really sure what to do about it, maybe just do nothing and hope their site dies because there're quite a bit of alternatives that use .apks

**Comment by sanatsathaye** [comment]
In my eyes (and many others') they are the most reputable site there is for downloading APKs. I don't think they will quite die any time soon but them releasing a proprietary format is pretty rubbish. I heard about the ad situation and blocked the app from all access to internet from my phone settings so I wouldn't have to deal with it but SAI would be the best solution.

**Comment by Aefyr** [comment]
Them having their own installer is totally fine, but making a format with DRM just so you have to watch their ads without having a choice to use other installers sucks

**Comment by IRGC** [comment]
@sanatsathaye see SAI in action at https://apkdl.in

**Comment by patrickdrd** [comment]
subscribe me

**Comment by souramoo** [comment]
I quickly wrote a decrypter for the format because I was bored, and I've also made it open source ;) Enjoy!

https://github.com/souramoo/unapkm

This might help to add apkm support to SAI by taking care of the heavy lifting and leaving you with a zip! :)

**Comment by Aefyr** [comment]
@souramoo, nice job, but I don't think I'm gonna add it in SAI because LazySodium library [seems to use pre-compiled binaries in it's repo](https://github.com/terl/lazysodium-android/tree/master/app/src/main/jniLibs/arm64-v8a), so SAI won't be compilable for F-Droid

**Comment by MrDodojo** [comment]
That's sad

**Comment by the4anoni** [comment]
> @souramoo, nice job, but I don't think I'm gonna add it in SAI because LazySodium library [seems to use pre-compiled binaries in it's repo](https://github.com/terl/lazysodium-android/tree/master/app/src/main/jniLibs/arm64-v8a), so SAI won't be compilable for F-Droid

But there wasn't any new Sai build on f-droid last time.

**Comment by Aefyr** [comment]
@the4anoni yeah, because there's an [ongoing issue with Shizuku's license](https://github.com/Aefyr/SAI/issues/81)

**Comment by shah-sudeep** [comment]
> Them having their own installer is totally fine, but making a format with DRM just so you have to watch their ads without having a choice to use other installers sucks. I [did reply to their tweet](https://twitter.com/polychromaticfx/status/1241463232151392256) with a question about .apkm, but it was ignored

Yeah having tons of app and making proprietary format is a crap, but what I liked about the app is that it detects the dpi and language automatically and also presents with the manual option to select those is quite nice feature to have. If we too could implement those features, it would be too good.

**Comment by Aefyr** [comment]
@shah-sudeep I want to implement that, but that will require a proper filepicker (that I've been trying to make for like a half of a year already, but none of like 3 attemps has succeeded lol, caching is hard). I'll probably give it another shot soon

**Comment by shah-sudeep** [comment]
> @shah-sudeep I want to implement that, but that will require a proper filepicker (that I've been trying to make for like a half of a year already, but none of like 3 attemps has succeeded lol, caching is hard). I'll probably give it another shot soon

Though illegal but try reverse engineering the apkmirror app and look into how they are doing so.

**Comment by shah-sudeep** [comment]
I do not know about the coding, but upto my knowledge ehat we need to do is, cache the .xapk/.apks and select by default 
1.base.apk
2.arm file
3.dpi file
4 lang file
(by getting info from system) and adding
option for manual selection as it is now in the Export option.
(Though easy to say but hard to do)

**Comment by Aefyr** [comment]
@shah-sudeep can you please share your opinion on #108?

**Comment by AndroidDeveloperLB** [comment]
Theoretically speaking, even though APKM is a terrible closed-source format, is it legal to handle it?
What if you have a closed sourced app yourself (And I know SAI is open sourced, of course) ? 

I never thought about it. 
Maybe it's similar to OpenOffice case of trying to handle DOC files? I guess it was legal back then, no?

**Comment by shah-sudeep** [comment]
I don't think we are going to support the crappy drm protected closed source .apkm format, 
And in my view we shouldn't do.
I hate the fact that apkmirror invested so much resources just to make their own format installable through their own app only.


Issue can be closed imo.

**Comment by AndroidDeveloperLB** [comment]
Is it legal though?

**Comment by Aefyr** [comment]
[APKMirror said that they may move to a normal ZIP format](https://github.com/android-police/apkmirror-public/issues/119#issuecomment-605518136). I'm kinda waiting for updates on that.

**Comment by shah-sudeep** [comment]
> [APKMirror said that they may move to a normal ZIP format](https://github.com/android-police/apkmirror-public/issues/119#issuecomment-605518136). I'm kinda waiting for updates on that.

Let's hope so, I too saw that post just few minutes ago.
This would be better bcoz everyone hated the fact that they made their format encrypted.
Also they shouldn't have gone so far by spending so much resources just to make profit through their app. Users who contributed by uploading app on their platform were too angry and were frustrated with their scheme.

**Comment by japzone1** [comment]
> Is it legal though?

Clean room reverse engineering of a format has never been illegal (See emulators running game ROMs). As long as you don't open up their app and steal their code, they can't do anything to you legality wise.

Theoretically they could still try to sue you into the ground, like Sony did with Beem despite losing the case, but I doubt APKMirror would do sick the thing as they probably don't have the resources, and they/Android Police would get a ton of backlash from the community(which they already seen to be just for even using apkm)

**Comment by AndroidDeveloperLB** [comment]
I see. Thanks for clarification.

**Comment by sanatsathaye** [comment]
> 
> 
> > Is it legal though?
> 
> Clean room reverse engineering of a format has isn't illegal (See emulators running game ROMs). As long as you don't open up their app and steal their code, and obtain the files via authorized methods (like downloading them from their own site), they can't do anything to you legality wise.

Simple solution then, call SAI an apkm emulator :D

**Comment by JosephTico** [comment]
If anybody here still wants to install an APKM file and doesn't want to use APKMirror's terrible installer, you can use the APKCombo installer: https://apkcombo.com/how-to-install/

It's basically a fork of SAI with APKM support.

**Comment by the4anoni** [comment]
> If anybody here still wants to install an APKM file and doesn't want to use APKMirror's terrible installer, you can use the APKCombo installer: https://apkcombo.com/how-to-install/
> 
> It's basically a fork of SAI with APKM support.

@Aefyr doesn't that thing breaks GPLv3 license?

**Comment by Aefyr** [comment]
@the4anoni I guess it does since I haven't found any licenses/source code/changes in the app or on their website. I've sent them a text about violating GPLv3, but I feel like it's gonna be ignored.

**Comment by the4anoni** [comment]
@Aefyr found another similar installer https://play.google.com/store/apps/details?id=io.apkmody.sai&hl=pl I couldn't find source code for it.

**Comment by sanatsathaye** [comment]
@Aefyr @the4anoni 

IIRC as per GPL you don't need to put up source code on a website or public Github, you only need to provide if you're requested to. So if you contact them and they provide source code by literally any means (zip, USB drive/CD rom physically mailed to your address, written down on paper then scanned with a printer and then have a pigeon poop on it and have it sent over by glueing it to a snail) they have not violated anything.

Of course, 95% people who don't provide source code don't and won't actually do that but just saying.

**Comment by Aefyr** [comment]
@sanatsathaye doesn't [this](https://www.gnu.org/licenses/gpl-faq.html#AnonFTPAndSendSources) require you to provide source via internet if you distribute the app via internet?

**Comment by AndroidDeveloperLB** [comment]
This is interesting.
This license means that the entire app should be open sourced, or just the files that still exist in both?
I never used such a license before, so I wonder about other repositories too.
For example, if a repository has just a library which doesn't even have UI, is it ok to publish only itself as open sourced, but the app will remain closed sourced?
What if the app that uses the library doesn't have any changes to the library in this case? Would it still need to publish it as open sourced?

**Comment by Aefyr** [comment]
Disclaimer: I'm no legal expert
> This license means that the entire app should be open sourced, or just the files that still exist in both

It doesn't have to be open sourced, like you could make a fork of a GPLv3 licensed work for personal use and not share it's source with anyone. But if you share the compiled version of the work, you also have to provide it's source code.

> For example, if a repository has just a library which doesn't even have UI, is it ok to publish only itself as open sourced, but the app will remain closed sourced?

Definitions in GPLv3 state `To "modify" a work means to copy from or adapt all or part of the work
in a fashion requiring copyright permission, other than the making of an
exact copy.  The resulting work is called a "modified version" of the
earlier work or a work "based on" the earlier work.`. So, I think your app would be considered a modified version of the lib. That being said, if you hold the copyright for the lib, you can do whatever you want with it.

> What if the app that uses the library doesn't have any changes to the library in this case? Would it still need to publish it as open sourced?

Same as above I think.

**Comment by AndroidDeveloperLB** [comment]
@Aefyr  I mean publishing an app on the Play Store.
I still don't understand it then.
It says that if I don't use a copy of it (" other than the making of an exact copy.") , it's modified.
This means that if I use a copy of it, and don't modify it, it's safe to use it. 
This could be a nice approach for libraries case, if the developer of the app promises he didn't change anything at all about the library, and uses it as if it was closed source. 

Isn't it correct?

Of course, here it's quite impossible, because this repository has UI and I don't think it's modular enough to be used with a different UI.

I ask in general. For example, suppose someone uses this license for some ZIP-handling library, and I use it and publish an app on the Play Store. Would I have to open source my entire app, even though I didn't change the code of the library, and just used it via gradle dependency ?

**Comment by Aefyr** [comment]
> This could be a nice approach for libraries case, if the developer of the app promises he didn't change anything at all about the library, and uses it as if it was closed source.

Well, the [FAQ says that you have to license your work under the same license if you use a GPL licensed library](https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL). It doesn't say what exactly in the licence text enforces that, but I guess that counts as adapting work because the resulting app isn't just an exact copy of the library.


> Of course, here it's quite impossible, because this repository has UI and I don't think it's modular enough to be used with a different UI

Yeah, not separating code in modules in SAI to begin with was quite a mistake and now it's too much of a mess to fix it.


> I ask in general. For example, suppose someone uses this license for some ZIP-handling library, and I use it and publish an app on the Play Store. Would I have to open source my entire app, even though I didn't change the code of the library, and just used it via gradle dependency ?

I think you'd have to, and that's probably the reason why Apache 2.0 seems to be much more popular with libraries.

**Comment by souramoo** [comment]
> @Aefyr I mean publishing an app on the Play Store.
> I still don't understand it then.
> It says that if I don't use a copy of it (" other than the making of an exact copy.") , it's modified.
> This means that if I use a copy of it, and don't modify it, it's safe to use it.
> This could be a nice approach for libraries case, if the developer of the app promises he didn't change anything at all about the library, and uses it as if it was closed source.
> 
> Isn't it correct?
> 
> Of course, here it's quite impossible, because this repository has UI and I don't think it's modular enough to be used with a different UI.
> 
> I ask in general. For example, suppose someone uses this license for some ZIP-handling library, and I use it and publish an app on the Play Store. Would I have to open source my entire app, even though I didn't change the code of the library, and just used it via gradle dependency ?

IANAL, but I think yes your app would need to be GPL if the library was GPL, it's by design a "viral" or copyleft license designed to make as much software as possible free as in beer. However, in reality most libraries are not licensed under GPL for this exact reason that it would put people off using it, and it's why the LGPL exists, so your app linking to an LGPL library does not also need to have the same license. In Java I've found most libraries to be one of the other more permissive licenses, such as Apache that do not require this of apps using their code.

Sources:
https://www.cnx-software.com/2011/10/10/open-source-licenses-overview-gpl-lgpl-apache-bsd/amp/
https://stackoverflow.com/questions/1114045/gpl-and-lgpl-open-source-licensing-restrictions
https://stackoverflow.com/questions/3500388/finding-out-the-licenses-of-jar-libraries

**Comment by AndroidDeveloperLB** [comment]
So according to what you guys wrote, using any repository that has GPL, even if it has a simple function - will require my own app be open sourced too.

This indeed sounds like a very annoying requirement. I have no idea why this license exists. Sounds like the trolling license to me :(

Anyway, thank you for the insights.

**Comment by sanatsathaye** [comment]
@Aefyr oops guess I missed that text. That said I wonder if the minutiae of GPL has ever been tested in court.

@AndroidDeveloperLB GPL is great and has its uses. It's the reason why ROMs exist in the first place on android, since manufacturers are required to release kernel sources. IMO it is absolutely needed due to the principles it is based on. 

But yes it is very aggressive and hence most libraries you find are based on permissive licenses; big companies won't touch it at all since they wouldn't want to be held responsible for anything. For example when the Android 3.0 Honeycomb was initially released Google never released the source. Licenses like those give more power to corporations than to the principles of FOSS.

**Comment by AndroidDeveloperLB** [comment]
An OS or its core is not a library, though some parts of it should be modularized and be free for all to use however they wish (general stuff).
It could be good for OS (or at least its core) to stay forever open sourced, to make it clear to whoever can how to fix it .
But I don't see much point for it on libraries. Libraries are supposed to assist apps, and sometimes apps need to modify them to fit their needs. It could be fine to request that the library's changes would be open sourced, but forcing the entire app to be open sourced... That's too much.

**Comment by TPS** [comment]
.
> But I don't see much point for it on libraries. Libraries are supposed to assist apps, and sometimes apps need to modify them to fit their needs. It could be fine to request that the library's changes would be open sourced, but forcing the entire app to be open sourced... That's too much.

That's why there's the [*L*GPL](https://en.m.wikipedia.org/wiki/GNU_Lesser_General_Public_License).

**Comment by AndroidDeveloperLB** [comment]
@TPS Isn't it the one that forces whoever uses it to also make the entire derivative be open sourced , even if you didn't change any of its files?

**Comment by TPS** [comment]
Read that link that I posted.  IANAL, but I believe that the LGPL only requires publishing any changes made to the _linked_ e.g., library.  It doesn't seem to require anything of the sort from the _linking_ e.g., app.

**Comment by AndroidDeveloperLB** [comment]
@TPS  English isn't my main language, and I'm terrible with law-related terms even in my own language.
I wish there was a simpler, super short way to understand the licenses. 
I only know that the safest licenses to use (meaning without fear of being sued for using them in any way I want) are Apache and MIT. Apache seems like the most common one on Github.

**Comment by TPS** [comment]
Unfortunately, the law _is_ too complex to make a simpler version binding. Try [an explanation in a different language](https://en.m.wikipedia.org/wiki/GNU_Lesser_General_Public_License#/languages).  A good shorter English explanation/comparison I found is [GitHub's own; the LGPL is currently the 3rd 1](https://choosealicense.com/licenses/).

**Comment by AndroidDeveloperLB** [comment]
Oh, so LGPL means you can use it without any limitations or requirements, but if you change it, you have to publish the code of what you used after the changes.

If you use Github for forking and having changes there, I guess it could be a nice solution.

**Comment by TPS** [comment]
AFAICT, _all_ the GPLs mean basically that, but each has slightly different nuaces beyond that.  Do compare the different licenses on that GitHub [ChooseALicense.com](httpS://ChooseALicense.com); I generally point devs there, after reminding them that, whatever they choose, it must be compatible to the components _they_ used from _other_ folks.

**Comment by AndroidDeveloperLB** [comment]
Right. Thank you. 
Much a nicer approach than "You use it? Now your entire code has to be open sourced too!".

**Comment by AndroidDeveloperLB** [comment]
I was told that APKM will be ZIP based (without password):
https://github.com/android-police/apkmirror-public/issues/119#issuecomment-674263134

So I think SAI could some day support it too.

**Comment by AndroidDeveloperLB** [comment]
Closed because will be implemented?

**Comment by sanatsathaye** [comment]
@Aefyr , apkm is now unencrypted (example: https://twitter.com/ArtemR/status/1344427285856751618). Would love an implementation in SAI.

**Comment by AndroidDeveloperLB** [comment]
@sanatsathaye Is it for all of them on the website?

**Comment by TPS** [comment]
@AndroidDeveloperLB No, as the substance of that tweet is _(emphasis mine)_
> We've rolled out an update that removes encryption from .apkm files.
>
>**_I'll let it bake for a while and only apply to new bundles, and then reprocess all the existing ones if all goes well._**
>
> APKMirror Installer already knows how to treat both.

So, probably _not_ a good idea to close, as it looks like .APKMs will continue to exist, just eventually will all be unecrypted.

**Comment by japzone1** [comment]
@AndroidDeveloperLB Tweet says they're testing it on new uploads first, before going back and unencrypting everything. 

To test I downloaded some random apps from their recent uploads and was able to extract them like a normal ZIP file and manually open files. I then tried renaming from `.apkm` to `.apks` and SAI was able to open and install the app without issue. I was even able to long-press and use the System File Picker to manually force opening an APKM file in SAI and that worked too.

Next I tried downloading older versions from several days ago, and those didn't work.

So starting with uploads on December 30th, if SAI gains the ability to accept APKM extensions, SAI will be able to open all new uploads from APKMirror.

**Comment by AndroidDeveloperLB** [comment]
@TPS @japzone1 I see. Thank you guys.
As for SAI, I've checked the sample file and I see no reason it won't be able to handle it. It's just APK files inside with some extras as bonus that you don't really need.

**Comment by DraconicNEO** [comment]
Is this going to be implemented or is SAI only going to be for .apks ?

**Comment by japzone1** [comment]
> Is this going to be implemented or is SAI only going to be for .apks ?

It already has. I just installed an .apkm from APKMirror via SAI today. Give it a try.

**Comment by laymanstake** [comment]
I have never got official apkmirror or any other installer install any .apkm correctly. Not a single app ever installed since they switched to .apkm

**Comment by AndroidDeveloperLB** [comment]
@laymanstake The old way that apkm works is gone, probably because of how bad it was, especially in terms of performance, compared to ZIP based file-formats.
If you want to handle APKM, APKS, XAPK, and of course APK files, there are various options for you. 
Example is just unzipping the special ones and installing them together using adb command.
Another example is this app (which I created), that you open the file directly from your file-manager app (or any other app that would offer to use my app for it):
https://play.google.com/store/apps/details?id=com.lb.app_manager
