### ISSUE TITLE
Please remove restrictions on auto theme

### ISSUE THREAD

**Issue by dadaewq** [Aefyr/SAI#103]
Dark mode does not just appear in Android10. In fact, it existed many years ago. Dark mode, even android2.3 devices also support it.Many users always have a way to switch the night theme to the system even below Android 10.
So I think It's better to cancel the option to show the auto theme only on Android10 and above.

**Comment by Aefyr** [comment]
Indeed, it does seem to work with theme toggle in developer settings on Pie
