### ISSUE TITLE
Showing app icon in the installer menu

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#105]
File selection window in the Installer menu doesn't show the icon of the apk or apks files.
It would be easier for app selection for installing if icon too is shown in the file picker.

**Comment by shah-sudeep** [comment]
![IMG_20200329_184446](https://user-images.githubusercontent.com/62835068/77849734-8faeb200-71ed-11ea-8d22-9b159229f7fa.jpg)
![IMG_20200329_184516](https://user-images.githubusercontent.com/62835068/77849736-92110c00-71ed-11ea-9a54-96a64b2ed438.jpg)
![IMG_20200329_184540](https://user-images.githubusercontent.com/62835068/77849738-93423900-71ed-11ea-99e9-8039c30efe2f.jpg)
SS attached.

Bug1- Export files name contains ',' (comma) instead of '.' (dot).
Also export button is titled as 'Enqueue' (It's intentional as it means to be in queue) but 'Export' will be simple and easily understandable by all.

2.The exported .apks is simply zipped in deflate compression instead of at least Normal compression which doesn't use much resources but reduces exported file size.

**Comment by Aefyr** [comment]
> File selection window in the Installer menu doesn't show the icon of the apk or apks files.

That's in plans for the new filepicker

> Export files name contains ',' (comma) instead of '.' (dot)

That's a feature, see #53 

> but 'Export' will be simple and easily understandable by all

Can be changed, but there's literally 2 buttons there, so idk

> The exported .apks is simply zipped in deflate compression instead of at least Normal compression which doesn't use much resources but reduces exported file size

If actual compression is used, APK size will be unknown before reading it meaning you'll have to enable archive extraction to install such an archive

**Comment by Cyberavater** [comment]
How about using 7zip to determine APK size before-hand? And also use 7zip as a part of SAI's mechanism to let the user set the compression method and ratio? [Just a thought].

**Comment by Aefyr** [comment]
> How about using 7zip to determine APK size before-hand?

I'm not sure, how will 7zip solve that, can you elaborate?

> use 7zip as a part of SAI's mechanism to let the user set the compression method and ratio

I don't want to use a compression method that is not deflate since Java's ZipInputStream/ZipOutputStream use deflate, I think it will add unnecessary complexity without much benefit

**Comment by shah-sudeep** [comment]
> > but 'Export' will be simple and easily understandable by all
> 
> Can be changed, but there're literally 2 buttons there, so idk
> 

"Enqueue" is okay when multiple file is selected for exporting but "Export" would be better for export of single apk/apks file.
![Screenshot_2020-04-16-07-25-56-540_com aefyr sai](https://user-images.githubusercontent.com/62835068/79406129-f4238c80-7fb5-11ea-86f9-503e824103ec.jpg)
Okay😊
![Screenshot_2020-04-16-07-26-07-127_com aefyr sai](https://user-images.githubusercontent.com/62835068/79406152-06052f80-7fb6-11ea-8514-fc8f4419a95f.jpg)
Not Okay☹️

**Comment by Aefyr** [comment]
> "Enqueue" is okay when multiple file is selected for exporting but "Export" would be better for export of single apk/apks file.

I can change them both to "Export", will that be fine? I don't think it makes a difference though

**Comment by shah-sudeep** [comment]
> I can change them both to "Export", will that be fine? I don't think it makes a difference though
>
It do make difference for people like me who doesn't understand comples terms😜.
 Thank You

**Comment by Aefyr** [comment]
> It do make difference for people like me who doesn't understand comples terms😜.
> Thank You

Ok, changed in https://github.com/Aefyr/SAI/commit/9102c9ecf7b0c6c00423ecdf8db528e1730870c9
