### ISSUE TITLE
Add: Support for installing Android App bundle (.aab) files

### ISSUE THREAD

**Issue by E3V3A** [Aefyr/SAI#107]
Hi! 
I'm not sure if it's possible, but can you look into adding support for installing:
*`Android App Bundle (.aab)`* files? 

* https://medium.com/mindorks/android-app-bundle-aab-98de6dad8ba8

**Comment by Aefyr** [comment]
No. Not sure why would you want it anyway since only devs of an app can get it and they might as well convert it into a monolith APK/splits
