### ISSUE TITLE
Split parts selection problem

### ISSUE THREAD

**Issue by Aefyr** [Aefyr/SAI#108]
So, I've decided to make parts selection separately from a new filepicker after all, but I've checked a few archives from different sources and not all of them abide the standard splits naming scheme (for example Vanced). So, what should SAI do with those? Select all of the APK files with unrecognized names by default?

**Comment by Aefyr** [comment]
Ok, I've found out that each split has a "split" attribute in AndroidManifest.xml with its proper name, I'll look into Android binary xml parsing libs

**Comment by shah-sudeep** [comment]
Looking into each apk's manifest will make slow loading of split apk list.
While comparing the Vanced app what I found was, it do follow the format only for language split file but not for arch or lang or even base apk.
Either we can support for both naming scheme or request Vanced devs to change their naming scheme in support of .apks format compatibility.
First option sounds better as even .xapk format does the same as vanced. But names its base apk with package name.
But I can't say what to do with the naming of the base apk file.

**Comment by shah-sudeep** [comment]
Can we not support both naming scheme "split_config.arm.apk" and "config.arm.apk" ?
IMO this would be the best option to support part selection mechanism.
Also for the base apk too, it seems we will need to support both "base.apk" and "package.name.apk", but this may be difficult, or we can lookup for the manifest of the remaining file??

But naming scheme of vanced has caused it to not display the icon and other basic info as other app fails to detect the base file apk.

**Comment by Aefyr** [comment]
Actually parsing APKs ended up being quite fast, it takes about 150ms on my OnePlus 5T to parse Vanced and it has 70 parts. Even if it takes 10x as much time on lower tier devices it'd still be just 1.5 seconds, so, I guess, I'll just roll with that.
