### ISSUE TITLE
Some language file name missing...

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#114]
I found that the "config.tl" which is also a language file (Tagalog) was not identified as language file, it was in Unknown category.

This can be of any use for the language list: https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes
![Screenshot_2020-04-11-07-04-48-705_com aefyr sai](https://user-images.githubusercontent.com/62835068/79032437-27d17180-7bc6-11ea-87b7-cc90fc8ac60a.jpg)

**Comment by shah-sudeep** [comment]
Also keywords like "code for base APK", "resources for base APK", and "locale for base APK" is unnecessary in my view.
![IMG_20200411_073041](https://user-images.githubusercontent.com/62835068/79032485-a5957d00-7bc6-11ea-9f62-d8316d8a21d3.jpg)

**Comment by shah-sudeep** [comment]
![Screenshot_2020-04-11-07-46-56-050_com aefyr sai](https://user-images.githubusercontent.com/62835068/79032888-995eef00-7bc9-11ea-85ab-a25810dd48a3.jpg)
Although there is only 1 locale file it still is selectable or can be unselected.
It should be made unselectable like other split category when there is single file in this category too.
Also "Your language is English (or whatever is default lang) can be shown here too.
(Although most of us do know our system language)

**Comment by Aefyr** [comment]
> I found that the "config.tl" which is also a language file (Tagalog) was not identified as language file, it was in Unknown category.

It is indeed. SAI queries all languages Android knows to determine if a split APK part is a locale config part, not sure what to do about this language, don't really want to make an exception in the parsing process for it

> Also keywords like "code for base APK", "resources for base APK", and "locale for base APK" is unnecessary in my view.

Why? What if that's code for a dynamic feature?

> Although there is only 1 locale file it still is selectable or can be unselected.
> It should be made unselectable like other split category when there is single file in this category too.

Ability to deselect a part doesn't depend on parts count, it depends on device configuration. Though maybe making user's preferred language non-deselectable is a good idea

> Also "Your language is English (or whatever is default lang) can be shown here too.

Yeah, makes sense considering all other categories have a similar thing going on in their descriptions
