### ISSUE TITLE
Dynamic features split apk file are shown in Arch category

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#115]
Dynamic feature split apk file for arm64-v8a are shown in arch split category.
![Screenshot_2020-04-11-07-34-40-955_com aefyr sai](https://user-images.githubusercontent.com/62835068/79032680-21dc9000-7bc8-11ea-84e1-a46f9a84a714.jpg)
![Screenshot_2020-04-11-07-35-43-643_com mixplorer beta](https://user-images.githubusercontent.com/62835068/79032687-26a14400-7bc8-11ea-8b2f-dc138846d54e.jpg)

**Comment by shah-sudeep** [comment]
Also meta.json and icon.png files were not written inside the apks in previous version but it is now. what is the use of that file??

**Comment by Aefyr** [comment]
> Dynamic feature split apk file for arm64-v8a are shown in arch split category.

Sorry, in what else category should they be?

> Also meta.json and icon.png files were not written inside the apks in previous version but it is now. what is the use of that file??

They're used to provide some information about the application contained in a .apks file and were primarily added for installer Pro mode, so it can show app icon, name and version prior to installation

**Comment by Aefyr** [comment]
[I've made a description/specification for the meta format SAI uses ](https://github.com/Aefyr/SAI/blob/master/META-FORMAT.md)

**Comment by shah-sudeep** [comment]
>> Sorry, in what else category should they be?
> 
I got confused for this, although they are arm64 code but still they are dynamic features, so shouldn't those be in dynamic features category??
> > They're used to provide some information about the application contained in a .apks file and were primarily added for installer Pro mode, so it can show app icon, name and version prior to installation
>these info can be saved to saved to the cache file. Mixplorer can still manage to show the icon and version info without any info inside the apks file. Can't we do so??

**Comment by shah-sudeep** [comment]
> [I've made a description/specification for the meta format SAI uses ](https://github.com/Aefyr/SAI/blob/master/META-FORMAT.md)

what is the use of timestap metadata??

**Comment by Aefyr** [comment]
> they are arm64 code but still they are dynamic features

No, it's a arm64 code config split for a dynamic feature, dynamic feature APK itself appears in the dynamic feature category.

> Mixplorer can still manage to show the icon and version info without any info inside the apks file. Can't we do so

I'm not aware of how Mixplorer does that. From what I know, that is certainly possible, but would require copying the base APK file from the archive to a temp file to parse it, so I think those few kilobytes the meta information in a .apks file takes are totally worth it.

> what is the use of timestamp metadata??

Currently it isn't used by SAI, just thought it'd be nice to have when I was designing meta format
