### ISSUE TITLE
Internal File picker doesn't remember last location

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#116]
I keep most of my apks files to a specific folder but while I try to open those file from the SAI I always have to browse to that folder. If only we can directly go to the last visited folder while selecting the internal file picker, it would be too much time saving.

**Comment by Aefyr** [comment]
There's an option in settings to set home directory for file selection, does that work instead? (Because again, I don't really like current filepicker and I still plan to make a new one in the future, but if you really need this feature, I could add it)

**Comment by cmohan0004** [comment]
> There's an option in settings to set home directory for file selection, does that work instead? (Because again, I don't really like current filepicker and I still plan to make a new one in the future, but if you really need this feature, I could add it)

sir is it really necessary to confirm every install? suppose i picked 20 apps and when in tap to install i have to tap 20 time on "install" for every app, can u please do something for it without requiring root like batch install.

**Comment by Aefyr** [comment]
> sir is it really necessary to confirm every install?

You mean installation confirmation screen from Android? I don't think there's anything I can do about it since it comes from the system. You can try Shizuku installer though, it works the same as the rooted one.

**Comment by patrickdrd** [comment]
I don't like this filepicker either because it doesn't let me switch to my sd card :O

**Comment by Aefyr** [comment]
@patrickdrd, yeah, you have to long click install button to use system file picker to access sd card

**Comment by shah-sudeep** [comment]
> There's an option in settings to set home directory for file selection, does that work instead? (Because again, I don't really like current filepicker and I still plan to make a new one in the future, but if you really need this feature, I could add it)

Thank you, I missed that. It worked.
Yeah the UI looks a bit outdated, it would be better to change it as it is already in to-do list.

But still adding "remember last directory" will be even more useful. Although you change the UI, the function will remain same, isn't it??
What are we going to do with the scooped storage??

**Comment by Aefyr** [comment]
> Although you change the UI, the function will remain same, isn't it??

No, I'm planning on implementing a completely new filepicker that supports not just File IO, but at least SAF as well. That's why I'm having so much trouble with coming up with a good architecture for it.

> What are we going to do with the scooped storage??

SAI already supports SAF for all storage-related actions, so it will work on R. Current internal filepicker will break though.

**Comment by shah-sudeep** [comment]
> There's an option in settings to set home directory for file selection, does that work instead? (Because again, I don't really like current filepicker and I still plan to make a new one in the future, but if you really need this feature, I could add it)

Implementation of "remember last directory" for now unless we get new filepicker will be appreciated.
