### ISSUE TITLE
Normal apk file fails to install.

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#117]
My system is MIUI 11. I know I need to disable the MIUI optimization in order to install the split app. But to install a normal .apk app it shouldn't be the requirement. Still it is though.
All other app is able to install the apk file when permission to " install from unknown source" is given to those app. But SAI fails to do so.
 I tried by enabling and disabling the legacy installer but of no use. Actually I don't know what difference does it make except few changes in UI??
Pro mode enabled or disabled, still can't install. And the installer mode is rootless as my phone is not rooted.

I also like to inform that even the permission asking dialog doesn't appear when I tried to install the app. Although I manually enabled that permission but still failed to install.

**Comment by shah-sudeep** [comment]
![Screenshot_2020-04-15-14-12-19-239_com aefyr sai](https://user-images.githubusercontent.com/62835068/79316473-153b9d00-7f24-11ea-85d9-3246fa0c8b03.jpg)
For normal .apk file, while in pro mode , app installation page appears same as that of the split apk. It shouldn't be so, bcoz there is nothing to be select or deselect. 
Also neither app icon nor app label is shown. It is so because I think it is trying to find those info in icon.png and meta file which is not there as in package exported by SAI. What I found was that previously exported apks files which doesn't include those file, their package name is only shown without icon in the installer page.

I personally am against this extra files, it is like following the path of .xapk package.
Mixplorer is able to show info and icon of apk, apks, xapk all even without extra files. Following this method will be better.

**Comment by Aefyr** [comment]
Do you mean normal APKs do not install with MIUI optimization enabled? If so, that's because SAI uses [PackageInstaller API](https://developer.android.com/reference/android/content/pm/PackageInstaller.html) for all installations, regardless of whether app being installed consists of multiple APKs or not. Other apps most likely just create an ACTION_VIEW intent for APK files.

> I tried by enabling and disabling the legacy installer but of no use. Actually I don't know what difference does it make except few changes in UI??

It uses a different architecture, ways of installation are the same though. I can't remember why I left is as an option lol

> I personally am against this extra files

Why? And what's wrong with meta in .xapk files? It's not like they use DRM or anything, anyone can easily parse it.

> Mixplorer is able to show info and icon of apk, apks, xapk all even without extra files. Following this method will be better.

Yeah, but do you know the exact way it does it though?

**Comment by shah-sudeep** [comment]
> Do you mean normal APKs do not install with MIUI optimization enabled? If so, that's because SAI uses [PackageInstaller API](https://developer.android.com/reference/android/content/pm/PackageInstaller.html) for all installations, regardless of whether app being installed consists of multiple APKs or not. Other apps most likely just create an ACTION_VIEW intent for APK files.
> 
I mean to say normal .apk package file (not split apks). The single apk file should be able to install even though the optimization is disabled, isn't it? but here it doesn't.
>
> It uses a different architecture, ways of installation are the same though. I can't remember why I left is as an option lol
>
I don't know about the architecture, but what I know is that I didn't found any difference except UI which is not required to be changed.

> 
> Why? And what's wrong with meta in .xapk files? It's not like they use DRM or anything, anyone can easily parse it.
> 
There is nothing wrong with it. But few other apps which too allow backup of splits app doesn't include such meta file. So what I(personally) wanted was to have similarity in all apks files wherever it is packaged.
> 
> Yeah, but do you know the exact way it does it though?

> Sorry, I don't know the exact method but what is does to get the icon and version number is same as that of the normal apk file bcoz when the base.apk is changed to other than "base.apk" for apks and "package.name.apk" for xapk file it fails to read those info.

**Comment by Aefyr** [comment]
> I mean to say normal .apk package file (not split apks). The single apk file should be able to install even though the optimization is disabled, isn't it? but here it doesn't.

MIUI optimization disabled? What error do you get? I've just found and fixed a bug in pro mode that caused all single files, for which parser has returned an error, to not be installed, but I don't think that's your case

**Comment by Aefyr** [comment]
> Sorry, I don't know the exact method but what is does to get the icon and version number is same as that of the normal apk file bcoz when the base.apk is changed to other than "base.apk" for apks and "package.name.apk" for xapk file it fails to read those info.

Ok, I did add a method to retrieve app meta that just copies base APK into a temp file and parses it for meta in https://github.com/Aefyr/SAI/commit/1dee0b59acb2043440b580b4172740d61d797cf0. This feature is only used when SAI can't find meta information files in the source and the base APK file is less than 100MBs. It is also toggleable in settings, I've left it enabled by default for now, but I'm not sure if this is a good idea since copying may be quite slow on non-UFS devices. Also no cache or anything, it copies it every time even if it's the same file it's already parsed.

**Comment by shah-sudeep** [comment]
> > I mean to say normal .apk package file (not split apks). The single apk file should be able to install even though the optimization is disabled, isn't it? but here it doesn't.
> 
> MIUI optimization disabled? What error do you get? I've just found and fixed a bug in pro mode that caused all single files, for which parser has returned an error, to not be installed, but I don't think that's your case

https://drive.google.com/file/d/1IRGnefPA6fS3kXlWKPbnWru4ydZnbEeo/view?usp=drivesdk
Here's the recording.

**Comment by shah-sudeep** [comment]
> Ok, I did add a method to retrieve app meta that just copies base APK into a temp file and parses it for meta in [1dee0b5](https://github.com/Aefyr/SAI/commit/1dee0b59acb2043440b580b4172740d61d797cf0). This feature is only used when SAI can't find meta information files in the source and the base APK file is less than 100MBs. It is also toggleable in settings, I've left it enabled by default for now, but I'm not sure if this is a good idea since copying may be quite slow on non-UFS devices. Also no cache or anything, it copies the base APK every time even if it's the same file it's already parsed.

Okay let's see how it works, and what time does it take to load the meta.

BTW there may be difficulty for the apks files bcoz it is archive of the already archived apk. But for normal apk (single apk) there shouldn't be problem for parsing the meta of those, it is not needed to copy to temp folder for this action, isn't it?? I viewed the log of the Mixplorer and it seemed (not sure) that it too copies to temp folder to extract the meta from base.apk.

But for the normal apk file it is not same.

**Comment by Aefyr** [comment]
> Okay let's see how it works, and what time does it take to load the meta.

Complete process of parsing a 55MB APK file takes under 200ms on my OnePlus 5T.

> there shouldn't be problem for parsing the meta of those, it is not needed to copy to temp folder for this action, isn't it??

Doesn't fit in the architecture (which is already quite a mess), because all APK files are provided as streams since they may be inside an archive.

**Comment by shah-sudeep** [comment]
I think installation of normal apk package should be able to install like from any other file manager in following condition too:
Installation Method: Rootless
MIUI Optimization: Enabled

I know installation of split apks do require MIUI optimization to be disabled. But for the normal apk files which can be installed by any other apps should also be able to do so through SAI even when optimization is enabled.

**Comment by Aefyr** [comment]
> I think installation of normal apk package should be able to install like from any other file manager in following condition too:
> Installation Method: Rootless
> MIUI Optimization: Enabled

Why should they? SAI uses PackageInstaller API regardless of what you're installing. If you want to install them via system package installer, you can just open them with it to begin with.

**Comment by shah-sudeep** [comment]
> Why should they? SAI uses PackageInstaller API regardless of what you're installing. If you want to install them via system package installer, you can just open them with it to begin with.

I don't have any special purpose to do that, but I only wanted so because I trust in SAI and I don't want to give all apps permission to "install from unknown source".
I wanted to have that too here so that whenever I have to install any app whatever be itt type or format, all to be installed from one app, that's it.

**Comment by Aefyr** [comment]
> I only wanted so because I trust in SAI and I don't want to give all apps permission to "install from unknown source".

Well, Android won't let them install anything without a confirmation from you anyway. Or you can use the system Files/Downloads/Documents app.

So, SAI won't use system package installer app to install APKs because no SAI features will work with it, it would just open the system package installer app and let it install the app, which sounds pretty useless in SAI and it is the job of file managers.
