### ISSUE TITLE
File picker option appears everytime.

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#118]
While on Pro mode, we need to select the file picker dialog every time we try to install any file.
Please add option to remember so that only the selected file picker will open when clicking on the Install options. Both options should appear on the first time and a checkbox to make it default file picker will be nice. If I need only one then I can make it default or otherwise it will appear everytime unless I check on the checkbox option.
![Screenshot_2020-04-15-15-06-19-451_com aefyr sai](https://user-images.githubusercontent.com/62835068/79321885-bc700280-7f2b-11ea-8586-0424df3db691.jpg)

**Comment by shah-sudeep** [comment]
Want to add two more suggestions, although it's nothing related to functionality, it is for simple UI change.

1. Changing settings page , settings name font to Bold and the details of those settings font color a bit faded(lesser black than the name).

2. Install location selection dialog appears at the center while all other dialog appears at the bottom. same behavior would be better.

**Comment by Aefyr** [comment]
I don't know about the checkbox idea, seems less convenient to me than the current implementation.


> 1. Changing settings page , settings name font to Bold and the details of those settings font color a bit faded(lesser black than the name).

Those are default material preferences, I'm not sure why isn't secondary text color used for summaries in SAI though.


> 2\. Install location selection dialog appears at the center while all other dialog appears at the bottom. same behavior would be better.

Yeah, because it comes from preferences lib, it seems to be possible to change it, but I got stuck the last time I tried

**Comment by shah-sudeep** [comment]
> I don't know about the checkbox idea, seems less convenient to me than the current implementation.
>
I could have avoided 1 extra step if I used system file picker just by long pressing the install option. But the problem is that, I use internal file picker most and everytime I select the install option, instead of opening the internal file picker directly, it gives me dialog to choose between internal and system file picker. This takes 1 extra step everytime I try to install anything.
