### ISSUE TITLE
Found few split apks with Unknown category

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#119]
I don't know how much of help it will do, but still wanted to let you know about few apps where I found it's split app with unknown category.
![Screenshot_2020-04-15-15-04-49-861_com aefyr sai](https://user-images.githubusercontent.com/62835068/79322418-88e1a800-7f2c-11ea-809e-b7bbc9e4f5a1.jpg)
![Screenshot_2020-04-15-15-04-03-352_com aefyr sai](https://user-images.githubusercontent.com/62835068/79322428-8aab6b80-7f2c-11ea-92be-8797dc60112e.jpg)
![Screenshot_2020-04-15-15-02-29-223_com aefyr sai](https://user-images.githubusercontent.com/62835068/79322429-8b440200-7f2c-11ea-9cb7-b0fa87b1bb20.jpg)

Actually all are from the Facebook itself.🤔

**Comment by Aefyr** [comment]
Can you provide a .apks file for one of these apps? They all download as a single APK for me from Google Play and APKPure

**Comment by shah-sudeep** [comment]
> Can you provide a .apks file for one of these apps? They all download as a single APK for me from Google Play and APKPure

Actually what I did was exported those apks from the SAI itself. these were installed through play store though.
Where and how can I send those files??

**Comment by Aefyr** [comment]
> Where and how can I send those files??

I don't know, can't you just upload them to some cloud and post a link here?

**Comment by shah-sudeep** [comment]
https://drive.google.com/folderview?id=1IHAJrMG-ZW-nWZMhJ1PQdWqceZoYg9s4
All .apks files are inside this folder.

**Comment by Aefyr** [comment]
Thanks for uploading them. Those parts seem to be dynamic feature splits, but they don't have android:isFeatureSplit flag in their manifest for some reason. Facebook being Facebook I guess, not fixable.
