### ISSUE TITLE
Custom Installation page doesn't appear in system file picker

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#120]
*1. When pro mode in enabled, while I go through internal file picker, Custom installation page appears but when browsing through the system file picker this page doesn't appear. Is it intentional?? or an error?

*2. Also when selecting multiple file through system file picker, it takes those files as split files of a single app but when selected the same multiple files from internal picker, it do understand that there are two separate .apks file selected. This occurs either when selecting multiple apk or apks from system but if multiple part apk is selected from internal viewer it do take those as single app split parts. Thus both picker behaves separately with internal picker being correct but not system picker.

**Comment by shah-sudeep** [comment]
*3. In internal file picker, single tap on any file should open that file directly while on long pressing it should be selected to be able to select multiple files as like that of the system file picker or the export page.

**Comment by Aefyr** [comment]
> Is it intentional??

Yes, long click with Pro mode enabled works exactly the same as it would if Pro mode was disabled.

> In internal file picker, single tap on any file should open that file directly while on long pressing it should be selected to be able to select multiple files as like that of the system file picker or the export page.

I've already said it many times, but I don't really want to work on the current filepicker much, because it's bad to begin with, I want to make a new one in the future (seems like it's never gonna happen though lol)

**Comment by shah-sudeep** [comment]
![Screenshot_2020-04-16-21-35-33-883_com aefyr sai](https://user-images.githubusercontent.com/62835068/79478910-b3665a80-802b-11ea-8907-6e435839cc26.jpg)
*1 What I meant to say is that, above page appears only when file is selected from internal picker but when selected from system picker this "Custom Installation" page doesn't appear.

**Comment by shah-sudeep** [comment]
> I've already said it many times, but I don't really want to work on the current filepicker much, because it's bad to begin with, I want to make a new one in the future (seems like it's never gonna happen though lol)
>
Sorry to bother you again with this, won't happen in future.

**Comment by Aefyr** [comment]
> *1 What I meant to say is that, above page appears only when file is selected from internal picker but when selected from system picker this "Custom Installation" page doesn't appear.

Yeah, that's intentional, if you have an idea what long click with Pro mode enabled should do instead, I'd be glad to hear it.

**Comment by Aefyr** [comment]
Wait do you mean that app info/splits selection doesn't appear even if you pick an app using single click and then choose system filepicker?

**Comment by shah-sudeep** [comment]
> Yeah, that's intentional, if you have an idea what long click with Pro mode enabled should do instead, I'd be glad to hear it.
>
Sorry that I couldn't make you understand what I wanted to say. It's not about click or long click.
The thing is that, in pro mode whether I pick file/files from internal picker or system picker (let's forget the way to select those picker) ,the Custom Installation page should have appeared from where I could select or deselect the split parts. 
But here what happens is that, the split picker page only appears when selected from internal picker but doesn't appear when selected from system picker.

**Comment by shah-sudeep** [comment]
> Wait do you mean that app info/splits selection doesn't appear even if you pick an app using single click and then choose system filepicker?

Yes this is exactly what I wanted to say, as you said "app info/splits selection doesn't appear" when app is selected through the system picker. (it's not about how I selected that picker, either way is same, whether it is by long click or by clicking install button and then selected system picker it's same)

**Comment by Aefyr** [comment]
> > Wait do you mean that app info/splits selection doesn't appear even if you pick an app using single click and then choose system filepicker?
> 
> Yes this is exactly what I wanted to say, as you said "app info/splits selection doesn't appear" when app is selected through the system picker. (it's not about how I selected that picker, either way is same, whether it is by long click or by clicking install button and then selected system picker it's same)

That shouldn't be possible though, what exactly happens after you select files via SAF?

**Comment by shah-sudeep** [comment]
> That shouldn't be possible though, what exactly happens after you select files via SAF?

It simply tries to install the app as it was doing previously when there wasn't the "custom mode" through pro mode like that of in the older versions.

**Comment by Aefyr** [comment]
> It simply tries to install the app as it was doing previously when there wasn't the "custom mode" through pro mode like that of in the older versions.

That makes no sense, I have no idea how that could happen

**Comment by shah-sudeep** [comment]
> > It simply tries to install the app as it was doing previously when there wasn't the "custom mode" through pro mode like that of in the older versions.
> 
> That makes no sense, I have no idea how that could happen

So sorry I don't know what went wrong previously, but when I re-installed SAI , it worked as you described, from single click then SAF custom Installation page appears but from long click it works as if pro mode is disabled.
