### ISSUE TITLE
Suggestion for Export page

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#121]
1. When export is completed, it shows the notification. It would be more better if a toast message showing it's completion appears so that there won't be any need to view through the  notification when I am still on the app page.

2.
![IMG_20200416_083719](https://user-images.githubusercontent.com/62835068/79409921-d27ad300-7fbe-11ea-9259-ec65dc9fd9c4.jpg)
It seems that there is no use to write the package name twice for every file name bcoz everytime I found the same file name in the 1st and 3rd line except for the base.apk name.
I found the 3rd line unnecessary.

Custom installation page type UI would be better.

**Comment by Aefyr** [comment]
Ok, I've changed the top line to represent split part feature (just line in installer Pro mode) in https://github.com/Aefyr/SAI/commit/76d47b6f4729fb16625c166049541d7f8efe537e, haven't added categories though.



> 1. It would be more better if a toast message showing it's completion appears so that there won't be any need to view through the  notification when I am still on the app page.

I can do a notification and a toast if SAI is in foreground, but not a toast without a notification. Not sure if that's actually needed though.

**Comment by Aefyr** [comment]
2nd suggestion is implemented, and toast is no longer necessary with managed backups, so I'm closing this
