### ISSUE TITLE
Why does the SAI (github version) need network access?

### ISSUE THREAD

**Issue by KPSH7AmcSRcfCqdJ** [Aefyr/SAI#122]
Tested with this github version.
https://github.com/Aefyr/SAI/releases/tag/3.10

**Comment by Aefyr** [comment]
Because it uses Firebase

**Comment by KPSH7AmcSRcfCqdJ** [comment]
Remove from the github version or an option to disable it?

**Comment by Aefyr** [comment]
Why don't you just use the F-Droid version?

**Comment by KPSH7AmcSRcfCqdJ** [comment]
I don't like F-Droid. Updates too slow and I think it's better if the original developer does it.

**Comment by Aefyr** [comment]
I don't think there's an API to enable/disable Crashlytics programatically.

**Comment by KPSH7AmcSRcfCqdJ** [comment]
If there is no such thing, one must make a choice. Crashlytics ask if such an API exists or can be added in the future.

Leave everything as it is. You just have to trust F-Droid with all its problems.

Or you can remove them.

But please note.
Don't you think that only extremely complex applications need such a framework?

**Comment by Aefyr** [comment]
> If there is no such thing, one must make a choice. Crashlytics ask if such an API exists or can be added in the future.

Nevermind I found it, added a toggle in https://github.com/Aefyr/SAI/commit/14f95bf6c407c7174db8492e33456bab0dd94389.

> Leave everything as it is. You just have to trust F-Droid with all its problems.

You can always build FLOSS apps yourself.

> Don't you think that only extremely complex applications need such a framework?

No, I think any app requires analytics and errors collection. Also SAI is quite complex imo.
