### ISSUE TITLE
Mark already existing and older apps

### ISSUE THREAD

**Issue by KPSH7AmcSRcfCqdJ** [Aefyr/SAI#123]
Hello would it be possible to extend the filter function?

I would like it very much if there is a possibility that the SAI app makes a note in the overview under "Export". If there is an older version of the app (apk) stored in the folder, it mark in the overview.

If it goes please no color, like red is this app is saved, but an older apk version and green is the current apk version is saved.

I think it is better if it is described in text, e.g. old apk version saved. newest apk version saved.

**Comment by Aefyr** [comment]
SAI currently doesn't keep track of files it exports. Managed exports are kinda planned for the future though (probably, since there are actual backup solutions out there that support split APKs).

**Comment by Aefyr** [comment]
With the addition of managed backups in SAI 4.0, apps now have an icon that represents the latest backup version and there're filters for them as well
