### ISSUE TITLE
Error installing vancsd apk

### ISSUE THREAD

**Issue by 0xdevanshu** [Aefyr/SAI#124]

**Comment by 0xdevanshu** [comment]
This error pops up when installing you tube vanced apk.

Error:
INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113

**Comment by Aefyr** [comment]
Either there are no native libs for your device architecture in the APK or APK is corrupted

**Comment by 0xdevanshu** [comment]
Thanx for the reply, it turn out you were right it is due installing different architecture apk so I tweaked a bit and issue is now solved
