### ISSUE TITLE
3.10 failing to build on fdroid build server

### ISSUE THREAD

**Issue by Yannik** [Aefyr/SAI#128]
3.10 was tagged 12 days ago, yet it's still not on fdroid. Is there an issue with fdroid?

**Comment by Yannik** [comment]
Yeah, there is an issue with building on fdroid:
https://f-droid.org/wiki/page/com.aefyr.sai.fdroid/lastbuild_52
```
INFO: Creating log directory
INFO: Creating temporary directory
INFO: Creating output directory
INFO: Using git version 2.11.0
INFO: Building version 3.10 (52) of com.aefyr.sai.fdroid
INFO: Getting source for revision 3.10
INFO: Applying patches
INFO: Applying build.patch
ERROR: Could not build app com.aefyr.sai.fdroid: Failed to apply patch metadata/com.aefyr.sai.fdroid/build.patch
```

**Comment by Aefyr** [comment]
@licaon-kter can you take a look at this please? I also feel like `firebase-analytics` in https://github.com/Aefyr/SAI/commit/ee6c5db0d6a0e716ed43a9f84db0fe1de0699336 will break it again.

**Comment by licaon-kter** [comment]
Updated.

**Comment by Aefyr** [comment]
@licaon-kter thanks. Will close issue when it builds a new version

**Comment by Yannik** [comment]
@Aefyr @licaon-kter There's still no build of 3.10/3.11/3.12 available through fdroid.

**Comment by licaon-kter** [comment]
Not yet...

**Comment by Yannik** [comment]
It's finally available.
