### ISSUE TITLE
Issue in files exported through SAI

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#131]
Not sure if it is SAI problem or Mixplorer problem, but it didn't occur on apks exported from v3.9. After the inclusion of meta files it happens so from v3.10. Doesn't happen to zip created through any other file manager or mixplorer itself, but the .apks created through SAI shows this everytime.
![IMG_20200422_115011](https://user-images.githubusercontent.com/62835068/79946385-96001900-848f-11ea-97e9-15c0c150b502.jpg)
![IMG_20200422_115028](https://user-images.githubusercontent.com/62835068/79946422-b0d28d80-848f-11ea-9398-6f71c1ff03fb.jpg)
Although after refreshing file list it shows correct list.
Don't know why this happens in first place but it happens only on .apks files created by SAI, all other files shows correct list. So was wondering if there any problem with the archive created by SAI.

**Comment by Aefyr** [comment]
I don't think this is a bug with SAI. Nothing in the way ZIP is generated has changed with the addition of metadata and opening .apks file as an archive works fine in every ZIP tool I've tried (Solid Explorer, ZArchiver, 7Zip)

**Comment by shah-sudeep** [comment]
> I don't think this is a bug with SAI. Nothing in the way ZIP is generated has changed with the addition of metadata and opening .apks file as an archive works fine in every ZIP tool I've tried (Solid Explorer, ZArchiver, 7Zip)

Maybe there is something wrong with the Mixplorer itself.
