### ISSUE TITLE
Few UI related issues

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#132]
Please look at different UI of Installer page for different settings:
1.
![Screenshot_2020-04-22-11-57-26-597_com aefyr sai](https://user-images.githubusercontent.com/62835068/79947495-c34dc680-8491-11ea-8390-bac4abf61648.jpg)
Settings>>
Legacy:Off
Pro mode:Off

Install Button: 
short press>internal file picker
long press>>system file picker

2.
![Screenshot_2020-04-22-11-56-30-477_com aefyr sai](https://user-images.githubusercontent.com/62835068/79947534-d52f6980-8491-11ea-8acf-ce349a47bda5.jpg)
Settings>>
Legacy:Off
Pro mode:On

Install Button: 
short press>picker selector appears

long press>>system file picker (not necessary bcoz it does same function as with the pro mode off)
(If wondering what should be function of the long press, I have suggestion at the end of post)

3.
![Screenshot_2020-04-22-11-56-00-755_com aefyr sai](https://user-images.githubusercontent.com/62835068/79947592-ed06ed80-8491-11ea-98ad-e47b2b3037a5.jpg)
Settings>>
Legacy:On
Pro mode:On/Off (No difference bcoz pro mode doesn't work here)
Here too short click opens internal picker while long click opens system picker.

![IMG_20200422_121406](https://user-images.githubusercontent.com/62835068/79949673-9e5b5280-8495-11ea-8f81-7f0af0f03975.jpg)

Here Legacy installer comes in action, but this doesn't mean that there should be change in the UI of the app. All buttons are moved which is not necessary.

From all these long stories what I mean to say is that let's have same buttons and UI for all mode. Let us have two separate buttons at the place where "install" button is now located. So that from one we can select internal picker and from another we can select system picker, no need for long click or picker selector.

**Comment by shah-sudeep** [comment]
From the no. 3. settings i.e. when legacy installer is on, there appears a new settings icon on top left corner of the page which whiles clicked opens settings page as like that from the regular settings button on bottom toolbar but there's a little change here too.
settings page appears with header when opened from new button whereas no header when opened from toolbar.
![IMG_20200422_121816](https://user-images.githubusercontent.com/62835068/79950872-71a83a80-8497-11ea-9f9b-0e66721cf26a.jpg)

No Header
![Screenshot_2020-04-22-11-59-09-413_com aefyr sai](https://user-images.githubusercontent.com/62835068/79951076-c8157900-8497-11ea-95bf-7004e78d2f4c.jpg)

**Comment by shah-sudeep** [comment]
For the same condition when legacy mode is turned on,
Although Auto theme is on or off but the theme selector appears as if auto theme has never been there, but change in theme doesn't happen unless auto theme is turned off.
![Screenshot_2020-04-22-12-15-17-592_com aefyr sai](https://user-images.githubusercontent.com/62835068/79951622-c1d3cc80-8498-11ea-92ae-9f30ba89c1aa.jpg)

**Comment by shah-sudeep** [comment]
For all mode (whether legacy mode kicked in or not), it would be nice if the theme button on home page works as the quick theme switcher even in the auto theme mode by switching through the pre selected theme for light theme and dark theme. Bcoz for settings of those themes we can already go to the settings page and switch between them and save those there. Shortcut button for theme should work as shortcut for theme switching (although only in the auto mode)

**Comment by shah-sudeep** [comment]
And what does this new warning info means?
"Even turning MIUI optimization may do nothing"
Does this means that instead of getting fixed, is it totally broken??

Ah! and due to these new warning lines the upper portion of the warning gets hidden. Plz reduce the font size of those warning.
![Screenshot_2020-04-22-13-08-55-788_com aefyr sai fdroid](https://user-images.githubusercontent.com/62835068/79952739-98b43b80-849a-11ea-8c13-6f4c69091299.jpg)

**Comment by Aefyr** [comment]
Legacy mode is called legacy for a reason. I'm not working on it anymore.



> And what does this new warning info means?
> "Even turning MIUI optimization may do nothing"
> Does this means that instead of getting fixed, is it totally broken??

Some MIUI users have reported that turning off MIUI optimization resets app permissions, so I've added a warning that that may happen on some MIUI versions. And that other unexpected things may happen since it's MIUI.

> Ah! and due to these new warning lines the upper portion of the warning gets hidden. Plz reduce the font size of those warning.

It's scrollable

**Comment by shah-sudeep** [comment]
> Legacy mode is called legacy for a reason. I'm not working on it anymore.

I just thought that having one UI would be better, without changing any functionality.

> Some MIUI users have reported that turning off MIUI optimization resets app permissions, so I've added a warning that that may happen on some MIUI versions. And that other unexpected things may happen since it's MIUI.
Oh! this happened only for some? I too am one of them but I thought that it happened to all whenever optimization was kicked off.

> It's scrollable
But the blinking disappears (let's ignore that too)

**Comment by Aefyr** [comment]
> Oh! this happened only for some? I too am one of them but I thought that it happened to all whenever optimization was kicked off.

I have no idea tbh

> But the blinking disappears (let's ignore that too)

You mean goes off screen?

**Comment by shah-sudeep** [comment]
> You mean goes off screen?

No I mean the warning sign goes hidden inside the status bar, that's it. Nothing serious it's just an UI bug you can leave it if you want to, but it do make the impression a bit down.
![IMG_20200424_201020](https://user-images.githubusercontent.com/62835068/80223549-26915180-8668-11ea-8ee2-da522700ae15.jpg)

**Comment by Aefyr** [comment]
> No I mean the warning sign goes hidden inside the status bar, that's it. Nothing serious it's just an UI bug you can leave it if you want to, but it do make the impression a bit down.

There was a bug with scroll indeed, fixed in https://github.com/Aefyr/SAI/commit/4de3770de68006b5852701e4785bcf2814cbd422

**Comment by Aefyr** [comment]
The latest actual issue here (install button long click in Pro mode) has been fixed in https://github.com/Aefyr/SAI/commit/32bb9ab5eab270e27b710a8298ce74f29873c7b1
