### ISSUE TITLE
Replacement of default language split apk

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#133]
Though you previously mentioned
>"Ability to deselect a part doesn't depend on parts count, it depends on device configuration. Though maybe making user's preferred language non-deselectable is a good idea"

in older thread but...
Though we can install multiple language split but it becomes unusable as nowadays many app doesn't include option to change language.

It can be useful to install app in some other language other than system app if default language can be made deselectable.
But again, when there is single language split apk, it shouldn't be deselectable.

**Comment by Aefyr** [comment]
It doesn't seem to work that way, it just fallbacks to the locale embedded in the base APK which also makes the warning about no matching locale part invalid.

**Comment by shah-sudeep** [comment]
> It doesn't seem to work that way, it just fallbacks to the locale embedded in the base APK which also makes the warning about no matching locale part invalid.

Please don't close this issue for now. I will try to do so in some app with previous version SAI.
