### ISSUE TITLE
The scroll bar changes in the settings section

### ISSUE THREAD

**Issue by KPSH7AmcSRcfCqdJ** [Aefyr/SAI#134]
Hello,

I noticed that in the setting section when you see the scroll bar, when you scroll down (slowly scroll down), the scroll bar changes with every option.

--
SAI 3.11

**Comment by Aefyr** [comment]
That's just how RecyclerView works

**Comment by KPSH7AmcSRcfCqdJ** [comment]
Can this be changed?

Looks a little laggy and not so smooth.

**Comment by Aefyr** [comment]
The only thing I can do is hide it
