### ISSUE TITLE
Metadata Info addition

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#135]
As we have already included the meta file in the archive, now we should add some other basis info too there within the file. 
Like :
 Target SDK Version & Minimum SDK Version supported by the app as a lot of app (including Mixplorer) shows these info while showing the preview of app. It will be faster and easier to acquire these info if these infos are included in the meta file.

**Comment by Aefyr** [comment]
Ok, is there anything else to add?

**Comment by shah-sudeep** [comment]
> Ok, is there anything else to add?

There are others too but let us keep those for later on in version 2 someday. like PERMISSION and "split apk" name of all files included in the zipped file of .apks.

**Comment by Aefyr** [comment]
[V2 meta format](https://github.com/Aefyr/SAI/blob/master/META-FORMAT.md#metasai_v2json) introduced in SAI 4.0 now contains min and target SDK versions and if app is a split APK
