### ISSUE TITLE
File picker option

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#136]
To select directory for saving exported file a file picker dialog appears to select between internal and system picker but for the "Home Directory" no such option is there.

**Comment by Aefyr** [comment]
Because, as far as I know, you can't set starting directory for system filepicker

**Comment by shah-sudeep** [comment]
> Because, as far as I know, you can't set starting directory for system filepicker

Ah, that's it. thanks anyway. It got out from my mind.
