### ISSUE TITLE
User Interface Bug/Glitch

### ISSUE THREAD

**Issue by stevenfelix505** [Aefyr/SAI#137]
![Screenshot_2020-04-25-12-40-24](https://user-images.githubusercontent.com/57618009/80272436-7c5f0b80-86f3-11ea-8fdf-ddb2b6338cdb.jpg)
![Screenshot_2020-04-25-12-40-34](https://user-images.githubusercontent.com/57618009/80272438-85e87380-86f3-11ea-92e1-0a920025d59e.jpg)
![Screenshot_2020-04-25-12-40-45](https://user-images.githubusercontent.com/57618009/80272443-91d43580-86f3-11ea-81f0-3362f6650885.jpg)
![Screenshot_2020-04-25-12-40-50](https://user-images.githubusercontent.com/57618009/80272444-9862ad00-86f3-11ea-827e-2a73de87123a.jpg)
![Screenshot_2020-04-25-12-41-06](https://user-images.githubusercontent.com/57618009/80272446-a0225180-86f3-11ea-8378-8908caba4ddb.jpg)
![Screenshot_2020-04-25-12-47-36](https://user-images.githubusercontent.com/57618009/80272449-a7495f80-86f3-11ea-8f18-4fa87ee9cbef.jpg)
Tested on ASUS T00I (OS Android 5.0 Lollipop)
Can you fix them all?

**Comment by Aefyr** [comment]
I have no idea what could cause this
