### ISSUE TITLE
INSTALL_PARSE_FAILED_NO_CERTIFICATES Exit-code:4

### ISSUE THREAD

**Issue by Vodianoi** [Aefyr/SAI#140]
I tried to install vanced via SAI following the installation guide but I still get this error : 

`Rooted Installer error :

 Device: motorola moto g(6) | Not MIUI | Android 8.0.0 | Using ZipApkSource ApkSource implementation | SAI 3.12

Unknown error

Command: pm install-commit 905341309
Exit code: 4
Out:

=============
Err:
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl905341309.tmp/70.apk: /data/app/vmdl905341309.tmp/70.apk failed verification of META-INF/CERT.SF: Failed to verify signature: no verified SignerInfos]`

I patched my device using SmaliPatcher and Luckypatcher but nothing changed...

**Comment by Aefyr** [comment]
Well, this issue has nothing to do with SAI, if you're trying to install an unsigned app.
