### ISSUE TITLE
Failed to install Xiaomi Mobile

### ISSUE THREAD

**Issue by gejiawei007** [Aefyr/SAI#141]
When using miui12 20.5.14, permission is given to read and write photos and files on the device, but permission denied is still prompted when installing，The mobile phone has turned on developer rights

**Comment by gejiawei007** [comment]
![Screenshot_2020-05-18-17-37-15-125_com aefyr sai](https://user-images.githubusercontent.com/41323576/82197995-43027000-992e-11ea-968e-8f25e5fdec7d.jpg)

**Comment by Aefyr** [comment]
Have you disabled MIUI optimization in developer settings?

**Comment by gejiawei007** [comment]
> Have you disabled MIUI optimization in developer settings?
Thank you for your answer, just disable it. I did n’t read the MIUI check prompts carefully during installation
