### ISSUE TITLE
Checksum for apks file is not the same

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [Aefyr/SAI#142]
### Description
Hello,

if apks file is created for the same app (same app version, all parts selected, same Android device and Android version). 

Then the apks file for the same app always has a different checksum. Can you fix it that the checksum is always the same?

For apk file the checksum is always the same.

### Version
Android 9

SAI 3.12
https://github.com/Aefyr/SAI/releases/tag/3.12

**Comment by Aefyr** [comment]
That's because [meta file](https://github.com/Aefyr/SAI/blob/master/META-FORMAT.md#metasai_v1json) in .apks files contains export timestamp. Why would you need same checksum anyway?

**Comment by ndnddkoeo3dkej9** [comment]
> That's because [meta file](https://github.com/Aefyr/SAI/blob/master/META-FORMAT.md#metasai_v1json) in .apks files contains export timestamp. Why would you need same checksum anyway?

Checksum are important because them to check files for integrity.

There are also users who want to check if the uploaded apks file is the same.

Can you change it e.g. add an option in the settings where the checksum for apks file always stays the same when creating for the same app?

**Comment by Aefyr** [comment]
I mean why can't you just check APK files checksum?

**Comment by ndnddkoeo3dkej9** [comment]
> I mean why can't you just check APK files checksum?
For example for new games app to make all parts as checksum is too time consuming.

**Comment by Aefyr** [comment]
.apks files generated by SAI are uncompressed ZIP archives, I don't see how making a checksum of all individual .apk files in them will take noticeably more resources than making a checksum of a .apks file itself.

**Comment by ndnddkoeo3dkej9** [comment]
Because of the better overview and simplicity for the users.        The administration of all the individual parts in the Android File Explorer is tiring.

Maybe it is enough to disable the timestamp from the metadata as an option.

**Comment by Aefyr** [comment]
Ok, I'll add an option to use a constant fake timestamp to debug settings

**Comment by Aefyr** [comment]
Ok, I've tried adding a fake timestamp, but the hashes of archives are still different even though contents are the same, no idea how does that work.

**Comment by ndnddkoeo3dkej9** [comment]
This is not good. Thought the cause might have something to do with the timestamp.

Then don't add this fake timestamp option, because that won't solve the problem.

You said that apks file was like a ZIP file.

I simply used the standard file explorer to add a txt file to a ZIP file and did the same process again with the same txt file. Both ZIP files have the same checksum.

Why it does not work with apks files, I do not know. What happens if you ignore metadata completely?

**Comment by Aefyr** [comment]
I forgot ZIP has it's own timestamp for each file. It works fine if I set it.
