### ISSUE TITLE
After uninstalling the application installed in shizuku mode, the newly signed same application cannot be installed

### ISSUE THREAD

**Issue by starry925** [Aefyr/SAI#143]
When I install an application in shizuku mode, whether I uninstall it or not, another signed application installed later cannot be overwritten / updated and installed. After I uninstall it, it will prompt that it is different from the installed signature, but I am indeed  It ’s already uninstalled. I ca n’t reinstall the newly signed application. How can I solve it?

**Comment by Aefyr** [comment]
Sorry, I'm not sure what you mean

**Comment by kamolsrisan** [comment]
good
