### ISSUE TITLE
Set apk and apks path individually for exporting the apps

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [Aefyr/SAI#144]
Currently the same path is taken for apk and apks when exporting the apps.

**Comment by Aefyr** [comment]
Why? Also in the next SAI version (currently [managed-backups branch](https://github.com/Aefyr/SAI/tree/managed-backups)) exporting single APK as a .apk file, without packing it into a .apks file, will probably be abolished (unless export and backup concepts are separated, but for now I'm not sure if I'm gonna do that)

**Comment by ndnddkoeo3dkej9** [comment]
For a better overview and faster workflow. Then don't have to manually move the apk or apks file into the corresponding folder every time.

**Comment by Aefyr** [comment]
So, yeah, I've decided not to support backing up a single APKs as a .apks file for now due to metadata being packaged into a .apks file.
