### ISSUE TITLE
Suggestion: possible way to check if Xiaomi MIUI causes issues

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Aefyr/SAI#145]
Seems there is a way to detect it:
https://github.com/android-police/apkmirror-public/issues/116#issuecomment-630204596

> You can always check if MIUI optimizations are on by checking the "persist.sys.miui_optimization" system property (values are either 1 or 0). You can also use reflection on the "isXOptMode" method (no arguments, returns a primitive boolean) in class "android.miui.AppOpsUtils", but the result's meaning is reversed (true means that the user has opted out of MIUI optimization).

For some reason, though, SAI says it will be fixed on "MIUI 20.2.20 and up" . I can't find a proof of it. Is it still true? If so, can you please share a link about it? Is it for all of Xiamoi's devices, including all types of models (says on SAI only about "xiaomi.eu and eu-based ROMs") ?

**Comment by Aefyr** [comment]
Thanks for the information, I'll try to use that method to cancel the timer on MIUI disclaimer screen if MIUI optimization is disable. The information that PackageInstaller API is fixed on MIUI EU 20.2.20 and up comes from [this changelog](https://xiaomi.eu/community/threads/20-2-20-v2.54641/post-529659):
> Fix - Fixed compatibility with third-party installers, like Split APKs Installer (you can ignore the "MIUI detected" warning)

**Comment by AndroidDeveloperLB** [comment]
@Aefyr 
I see, but is it only for "xiaomi.eu and eu-based ROMs"  ? What about the rest? And how would you check it? 
I thought Xiaomi makes some base MIUI OS that is used for all, with minor changes, no?

BTW, they mentioned you app ! Congrats :)

**Comment by Aefyr** [comment]
> I see, but is it only for "xiaomi.eu and eu-based ROMs" ? What about the rest? And how would you check it?

I think so. I'm not sure how to tell MIUI variations apart, [currently I just skip the timer if MIUI version is 20.2.20+](https://github.com/Aefyr/SAI/blob/bd4d4eb37016711b6250caa276359f4bdad3d2fb/app/src/main/java/com/aefyr/sai/utils/MiuiUtils.java#L73).



> I thought Xiaomi makes some base MIUI OS that is used for all, with minor changes, no?

Sorry, not sure what you're trying to say. Xiaomi obviously makes the "official" MIUI that is the stock ROM for their phones, but I think there's quite a lot of custom ROMs based on it.

> BTW, they mentioned you app ! Congrats :)

Thanks :)

**Comment by AndroidDeveloperLB** [comment]
@Aefyr What do you mean "skip the timer" ? Meaning not showing any warning?

As for Xiaomi, I meant that whenever a user buys a Xiaomi device, doesn't it mean its OS is the same stock one as any other user that buys a Xiaomi's device? What are those versions? Are those custom ROMs ? When you say "xiaomi.eu and eu-based ROMs", what does it mean? Are those stock from Xiaomi? Does Xiaomi make more than those? If so, what is the situation with them ? Saying that it's specific to something brings a lot of questions about the existence of others.

**Comment by Aefyr** [comment]
> What do you mean "skip the timer" ? Meaning not showing any warning?

There's a 30 sec timer on the MIUI warning screen before you can continue.



> When you say "xiaomi.eu and eu-based ROMs", what does it mean?

Well, it means exactly what it says, xiaomi.eu is a specific custom ROM, it's not a stock ROM and it's not made by Xiaomi. Though AliExpress sellers used to sell (maybe they still do, idk) Xiaomi devices with custom ROMs, so you don't have to use Chinese version of MIUI while waiting for bootloader unlock timer.

**Comment by AndroidDeveloperLB** [comment]
So what do you mean by "skip the timer" ? It doesn't show this warning at all? 
Or it doesn't have a timer?

As for the ROMs, you say that only on custom ROMs it's fixed, and yet on stock of Xiaomi this issue will continue to exist?

**Comment by Aefyr** [comment]
> So what do you mean by "skip the timer" ? It doesn't show this warning at all?
> Or it doesn't have a timer?

You don't have to wait 30 sec before continue button becomes active.



> As for the ROMs, you say that only on custom ROMs it's fixed, and yet on stock of Xiaomi this issue will continue to exist?

No idea, all I know is that it's fixed on xiaomi.eu

**Comment by AndroidDeveloperLB** [comment]
Wait, you mean to tell me that users need to wait for 30 seconds before they can close this warning?
If so, that's not nice at all. Reminds me of all the trouble that Xiaomi has for its users. I once tried to enable USB debugging on Xiaomi device, and it was terrible, with so many waiting-times and even requirement to have Xiaomi account and SIM card inserted for some reason.

Please remove this waiting, if this is what I think it is. 

As for the ROM, I see. Thank you for this information. I don't think they've changed it.
What's the latest one of Xiaomi ? Maybe I could find a Xiaomi device with this version and do this check on it.

**Comment by Aefyr** [comment]
Yeah, you have to wait 30 seconds before you can close it. It only appears once though. I'm not going to remove it because no one used to read what it says before the timer. Some people still don't, but I'd say quite a bit less, based on GP reviews.

Not sure what the latest version of MIUI is, and it depends on the device, I guess their flagship devices get updates first.

**Comment by AndroidDeveloperLB** [comment]
But... 30 seconds ?!
That's even more than what Xiaomi does...
Why even have it ? Just have a checkobx saying "I understand" and make it 2 phases and that's it.
Why have to wait for whole 30 seconds...

**Comment by Aefyr** [comment]
> That's even more than what Xiaomi does...

They make you wait 72 hours to unlock bootloader, lol.

> Why even have it ? Just have a checkobx saying "I understand" and make it 2 phases and that's it.

I've considered making a quiz with question being "How do I fix  installation on MIUI?", but what if user doesn't know English and SAI has no translation for their language, so, I settled for the timer.


Not sure, how waiting 30 seconds once is a problem, it's about the time it takes to read that warning carefully. Plus, there's no timer on MIUI 20.2.20 and I'll use your suggested methods to skip it if MIUI optimization is already disabled.

**Comment by AndroidDeveloperLB** [comment]
72 hours? That's terrible. But I was talking about other things I've noticed, of enabling developer options stuff ...

What if the user already knows what he's supposed to do? Why force him to wait this long?
Why take one of the most annoying things and add it to just reading time... 

It's like those full screen ads that don't let you close them or skip them unless you see an entire 30 seconds of them.

Really hate those things.

**Comment by Aefyr** [comment]
> What if the user already knows what he's supposed to do?

Well, they won't have to wait if MIUI optimization is already disabled when I implement your suggestion.

I know that it's annoying, but it either that, or a ton of complaints from MIUI users about SAI not working on their device because they skipped the warning.

**Comment by AndroidDeveloperLB** [comment]
Saying that they won't see it if they disabled is kinda like a circular explanation. 

Having a checkbox or a slide-to-continue or something means the user understood it.
Having an ad-like screen is something to avoid on a tutorial page, even if the tutorial is important.

**Comment by AndroidDeveloperLB** [comment]
@Aefyr Thank you. Happy to help a bit.
