### ISSUE TITLE
Won't install on aftv2

### ISSUE THREAD

**Issue by niwi-hh** [Aefyr/SAI#146]
I can't install SAI on my Amazon Fire TV2 by sideloading. I always get an error message without any techical details .If you need any logs, please write were I could find them.

**Comment by Aefyr** [comment]
What's the full error log?

**Comment by Aefyr** [comment]
Oh, wait you can't install SAI? Then I don't know, what Android version is it running? Can you try installing it via adb to get error log?

**Comment by niwi-hh** [comment]
Well, with adb I can install SAI without any problems. I don't know why it doesn't work while installing locally but for me the problem us solved. Thanks.
