### ISSUE TITLE
Bug by design: on R, if you grant the app install-permission, it will be forced-stopped

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Aefyr/SAI#148]
Please consider checking it out:
https://www.reddit.com/r/androiddev/comments/gvhwzd/android_r_app_granted_install_permission_and_got/

https://issuetracker.google.com/issues/158018379

It will affect this app too.

**Comment by Aefyr** [comment]
I'm following that issue. If they don't fix it, I'll add a dialog that warns user that app will be killed and requests permissions prior to installation

**Comment by AndroidDeveloperLB** [comment]
I hope you won't need it. It's about as bad as the weird things Xiaomi comes up with.
