### ISSUE TITLE
Apks backup to apk not working

### ISSUE THREAD

**Issue by mastermark1983** [Aefyr/SAI#156]
it,s only the base.apk it,s not working for installing
Maybe a option from apks to armv64 armv7 .......apk

Grtz Mark

**Comment by Aefyr** [comment]
It's not supposed to. It's mostly a convenience thing for non split APKs that some users have requested

**Comment by mastermark1983** [comment]
Ok next update a paid option 😉👌👍

**Comment by Aefyr** [comment]
I've already said it before, but there will be no APK merging in SAI because it's useless, complicated and not allowed on Google Play

**Comment by mastermark1983** [comment]
Ok 👍👊
