### ISSUE TITLE
Install applications with data in internal memory

### ISSUE THREAD

**Issue by mrkietzataka** [Aefyr/SAI#157]
xapk is the solution to install applications with obb data, some applications have data in internal memory, which is not obb so what is the solution?
I have an application that installs the same data to the device's internal memory at / sdcard / and / sdcard / Android / data /. For example, the Navitel application has application data stored in the internal memory

**Comment by Aefyr** [comment]
FYI SAI currently doesn't support obb extraction. Android/data directory is app data directory, so it should be managed by a backup solution. But currently SAI backups just APK files.

**Comment by mrkietzataka** [comment]
Navitel app uses map data in /sdcard/NavitelContent, I want to pack zip apk file and app data when installing apk file at the same time extract data to sdcard

**Comment by mrkietzataka** [comment]
Here is a simple project to install apk file with obb in .xapk, you can upgrade xapk with obb https://github.com/KhunHtetzNaing/XAPKInstaller

**Comment by IRGC** [comment]
https://github.com/KhunHtetzNaing/XAPKInstaller/blob/master/app/src/main/java/com/htetznaing/xapkinstaller/Fucker.java
WoW nice file name 😁😅

**Comment by Aefyr** [comment]
The issue with obb in SAI is that installer architecture was never designed to handle anything besides APK files. I'm considering reworking it later though.

**Comment by mrkietzataka** [comment]
> https://github.com/KhunHtetzNaing/XAPKInstaller/blob/master/app/src/main/java/com/htetznaing/xapkinstaller/Fucker.java WoW nice file name

The developer has the idea of ​​naming the file

**Comment by Aefyr** [comment]
[Apparently Android 11 restricts access to Android/data and Android/obb directories](https://developer.android.com/preview/privacy/storage#file-access), [it also basically forbids custom file pickers on Google Play](https://support.google.com/googleplay/android-developer/answer/9956427) even though SAF file picker is pretty much useless when you need to filter files by something other than their MIME types that are hardcoded in Android, and with [hardware SafetyNet kinda killing root](https://www.xda-developers.com/safetynet-hardware-attestation-hide-root-magisk/), I honestly have no idea what to work on in SAI anymore. [There's also a special permission required to be able to query all installed apps on device](https://developer.android.com/preview/privacy/package-visibility#all-apps), but there's no GP policy for that yet, hopefully backup apps will fall under applicable cases.
