### ISSUE TITLE
Allow multiple single APK to be exported as .apk file

### ISSUE THREAD

**Issue by Rumpotkimhy** [Aefyr/SAI#158]
Hello,

I use SAI version 4.2 and have only single APK. There is no split APK on my smartphone.

If I select multiple apps, but the apps only have single APK and export, everything is saved as .apks file. But I would like to save it as .apk file.

This option is missing. It would be good if an option can be added. Thank you.

**Comment by Aefyr** [comment]
If I'm gonna add it, I have to add proper batch actions first. Thought I'm not sure what would be the use-case for this feature.

**Comment by IRGC** [comment]
Is this even possible? Do we need signing key of original developer to sign it?🤔🤔🤔

**Comment by Aefyr** [comment]
@IRGC I think they mean exporting non-split apps as a .apk file instead of making a .apks backup of them.

**Comment by Rumpotkimhy** [comment]
Currently, I can export non-split-apps individually as apk file.

When I select multiple non-split apps, the export is always as an apks file.


for me is
apk = traditional apps (non-split apps)

apks = split apps
