### ISSUE TITLE
Installation failed [Xiaomi Mi 8]

### ISSUE THREAD

**Issue by KoreanPizzaGuy** [Aefyr/SAI#16]
I must to turn off miui optimizations but I don't have it in developer options. Only I have [Notify about high-risk features].
rom: MIUI 10 9.7.11 beta

**Comment by Aefyr** [comment]
Just install AOSP-based ROM then, lol

**Comment by KoreanPizzaGuy** [comment]
D: but I don't want AOSP-based ROM

**Comment by Aefyr** [comment]
Then you can try rooted installer

**Comment by KoreanPizzaGuy** [comment]
I don't wanna root my device because I have bank app and it won't work anymore

**Comment by Aefyr** [comment]
Use Magisk Hide?

**Comment by AndnixSH** [comment]
Split apk mechanism is such a pain
You can go to apkcombo and download single apk
It's safe since it download directly from play store
