### ISSUE TITLE
Support installation of ordinary apk files.

### ISSUE THREAD

**Issue by 742903746** [Aefyr/SAI#164]

**Comment by Aefyr** [comment]
It is already supported though? Or do you mean some specific case?

**Comment by dadaewq** [comment]
> It is already supported though? Or do you mean some specific case?

hope SAI  can deal with  <action android:name="android.intent.action.INSTALL_PACKAGE" />

**Comment by Aefyr** [comment]
@dadaewq Why? That action is deprecated. SAI can handle ACTION_VIEW for .apks files, I guess ACTION_VIEW support for .apk files will make sense

**Comment by dadaewq** [comment]
> @dadaewq Why? That action is deprecated. SAI can handle ACTION_VIEW for .apks files, I guess ACTION_VIEW support for .apk files will make sense
That's right, that's what I want to express.

**Comment by Aefyr** [comment]
If that's not what you meant, @742903746, please reopen this issue and explain what you meant
