### ISSUE TITLE
Add a way to delete older backups

### ISSUE THREAD

**Issue by NULL0B** [Aefyr/SAI#167]
Hello i was wondering if could be possible to add a list to select older duplicated backups to delete. Because go over each backups deleting older isn't nice : /. I have to backup all my apps because in my country the internet is not good. And i hope to SAI could be the backup manager dreamed.

**Comment by Aefyr** [comment]
You mean like delete all backups for selected apps except for the latest ones?

**Comment by NULL0B** [comment]
Yes but in a list to select what to delete and what not
