### ISSUE TITLE
support for now unencrypted .apkm format

### ISSUE THREAD

**Issue by shah-sudeep** [Aefyr/SAI#171]
Now apkmirror app has been updated and they have now opened their encrypted .apkm format to the unencrypted zip format. Now as the files are made open can we support that format too in the SAI, or we still can't bcoz their format is still proprietary? 
If we can't support their format then the only way will be to change the file extension and use the SAI app to install those files, bcoz we still can't use their app to install any application bcoz of the tons of ads everytime we try to install a new app.

**Comment by astramak** [comment]
> Now apkmirror app has been updated and they have now opened their encrypted .apkm format to the unencrypted zip format. 

Where i can read about it?

**Comment by shah-sudeep** [comment]
one more question, a bit off topic.
Can an application file packaged with some other method other than zip , launched or even installed on the android system. We can place those files on the required location by using root or by using inputstream method, but can we run that app if it is compressed with some other method?

**Comment by MrIkso** [comment]
Duplicate #100

**Comment by DraconicNEO** [comment]
It would be good to use the documentation from [This project](https://github.com/souramoo/unapkm) to fully add support for the .apkm encrypted or not.
