### ISSUE TITLE
Unknown package

### ISSUE THREAD

**Issue by Jisu-Woniu** [Aefyr/SAI#175]
![Screenshot_2020-10-12-16-49-04-691_com.aefyr.sai.fdroid.jpg](https://user-images.githubusercontent.com/31986081/95726021-f76cac00-0caa-11eb-91de-53bc751fdc54.jpg)
This package should be intended for Chinese translation.

**Comment by MuntashirAkon** [comment]
Merging #174 will fix this issue.
