### ISSUE TITLE
.apkm split apk format

### ISSUE THREAD

**Issue by thetoolz** [Aefyr/SAI#177]
new split apk file format (.apkm) https://www.androidpolice.com/2020/03/24/apkmirror-installer-for-android-now-in-public-beta-lets-you-install-app-bundles-and-apks/
but it's encrypted.

The tool unapkm 
https://github.com/souramoo/unapkm
decrypts them into a more standard APKS format that can be opened with 7zip so you can install it yourself with https://github.com/Aefyr/SAI
or another open source tool - installing apps shouldn't be a proprietary feature!

**Comment by chromer030** [comment]
Please add support for this format
