### ISSUE TITLE
[Feature Request] APKM format support

### ISSUE THREAD

**Issue by chromer030** [Aefyr/SAI#188]
Hi , thank you for this useful app.
Please add support for apkm files , on apkmirror.com  there is a lots of apps with this format and currently SAI cannot recognize and install them. 
Thank you again.

**Comment by Aefyr** [comment]
Added support in https://github.com/Aefyr/SAI/commit/b2b8b4683d405cb70f303548098c6eedb380bcca. Only for unencrypted ones tho.
