### ISSUE TITLE
install split_config.armeabi_v7a.apk for Androidx86

### ISSUE THREAD

**Issue by youling257** [Aefyr/SAI#19]
some app no x86 library, only has armv7 library, Androidx86 enable houdini to run armv7 library app.
now, split apks no split_config.armeabi_x86.apk, only has split_config.armeabi_v7a.apk, but SAI won't install split_config.armeabi_v7a.apk for Androidx86.

Root安装器 错误:

 设备: Android-x86 Pixel XL | Not MIUI | Android 7.1.2 | Using ZipApkSource ApkSource implementation

Command: pm install-commit 389848273 
Exit code: 4
Out:

=============
Err:
Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]

**Comment by youling257** [comment]
PicsArt-v12.7.4_build_993812704-Mod.apks install failed on Androidx86.

**Comment by Aefyr** [comment]
split_config.armeabi_v7a.apk in that .apks archive is corrupted - it has compressed native libraries while base apk has ["extractNativeLibs=false" manifest flag](https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs), hence Android expects libraries to be uncompressed and aligned by 4096 bytes. Also that file hosting is trash.
