### ISSUE TITLE
[Feature Request] Support for Sui mode (compatible Shizuku API)

### ISSUE THREAD

**Issue by naicfeng** [Aefyr/SAI#191]
See https://github.com/RikkaApps/Sui

For existing apps which already supports Shizuku, add support for Sui (including changes for Shizuku API v11) should only takes less than half an hour.

Please

**Comment by Aefyr** [comment]
Added support for Sui in https://github.com/Aefyr/SAI/commit/a98f671e7d1b275c987dc0002fafd15635471a57.

**Comment by Aefyr** [comment]
Although it's kinda useless without actually using the IPC stuff

**Comment by naicfeng** [comment]
Is work, Thanks
