### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rfego** [Aefyr/SAI#193]
INSTALL_FAILED_INVALID_APK: /data/app/vmdl2025294076.tmp/1.apk signatures are inconsistent
Файл весит 3,8 гигов 
Редми ноут 9 про 12.0.3 
Выполнил как было сказано в предупреждении все. 
В чем может быть проблема?

**Comment by AinzTheSupremeOne** [comment]
Make sure you have downloaded the apk/app bundle from an official source or a trusted source. Android won't let an app update be installed if the signature of the update is different from the already installed version of the app. Disable sign apks in SAI settings as well. 
![IMG_20210205_190058](https://user-images.githubusercontent.com/50095635/107039945-8f574e00-67e4-11eb-90f9-cfcaa35c2ade.jpg)
