### ISSUE TITLE
Package has failed verification

### ISSUE THREAD

**Issue by CoreyVidal** [Aefyr/SAI#196]
Hello. I am trying to install [this bundled package for Google Recorder](https://www.apkmirror.com/apk/google-inc/google-recorder/google-recorder-2-1-347255046-release/google-recorder-2-1-347255046-android-apk-download/).

I'm on Android 11 on a Samsung Galaxy Note 10+ (not rooted).

First I tried rootless both with and without "Sign APKs" toggled. It would say

```
Package has failed verification
INSTALL_FAILED_VERIFICATION_FAILURE
```

It didn't return any other information.

Then I tried Shizuku, with its new Android 11 feature to use "Wireless debugging".

I tried both with and without "Sign APKs" toggled. I got this error every time:

```
 Device: samsung SM-N975W | Not MIUI | Android 11 | Using FilterApkSource ApkSource implementation | SAI 4.4

Package has failed verification

Command: pm install-commit 459467063
Exit code: 1
Out:
Failure [INSTALL_FAILED_VERIFICATION_FAILURE]
=============
Err:
```

Any thoughts?

**Comment by AinzTheSupremeOne** [comment]
Disable Google Play protect and this toggle in dev settings. 
![IMG_20210213_120046](https://user-images.githubusercontent.com/50095635/107843685-2f1f6800-6df3-11eb-8c2f-1c28b97f9bb5.jpg)
