### ISSUE TITLE
Not able to install Split Apps in MIUI 10( Pie)

### ISSUE THREAD

**Issue by Mridumoloy** [Aefyr/SAI#20]
I'm not able to install any split apps in my Redmi Note 7S(India). I'm using MIUI 10 10.3.6.0. I'm getting the following error code when I'm trying to install any spilt apps 
"Rootless installer error:
![Screenshot_2019-08-12-08-37-55-860_com aefyr sai](https://user-images.githubusercontent.com/54013172/62844136-cc6c7e00-bcdc-11e9-9322-bd573d9f3cd3.png)

 only DEFLATED entries can have EXT descriptor"
I've also disabled MIUI Optimisation in developers settings. Please help me with what to do.

**Comment by Aefyr** [comment]
Something is wrong with the archive with apks

**Comment by lyndmi** [comment]
What apps are you trying to install?

**Comment by Mridumoloy** [comment]
PicsArt Studio Premium bundle purchased from Amazon App Store. The apks are totally correct. They've successfully installed on a different device (OnePlus 7Pro) but not on Redmi.
:)

**Comment by Aefyr** [comment]
@Mridumoloy if your Redmi runs MIUI, have you disabled MIUI optimization in developer settings?

**Comment by Mridumoloy** [comment]
MIUI Optimisation is already disabled

**Comment by Aefyr** [comment]
Try extracting the .apks archive with any file manager app and either just selecting plain APKs from it in SAI or putting the archive back together with ZArchiver/Solid Explorer
