### ISSUE TITLE
Some suggestions about SAI

### ISSUE THREAD

**Issue by Edfgdz** [Aefyr/SAI#202]
1.Show how much progress has been finished when install each apks file because some apks file size too huge so user don't know when it will finish installing

2.Let user could directly install zip file with SAI in File Manager.

At present look like when user want to install app bundle with zip extension SAI doesn't appear in it.

**Comment by Edfgdz** [comment]
![2021-3-17_18-22-53](https://user-images.githubusercontent.com/26460124/111453233-51880680-874e-11eb-820a-ffecf741ee0f.PNG)

**Comment by Aefyr** [comment]
1. That's not possible because Android doesn't really report installation progress, see how the system package installer progress bar works (it's useless).

2. I guess I could add that with a setting to turn it off.

**Comment by Edfgdz** [comment]
Have one problem for this feature. 

When SAI support install zip bundle file from file manager and what if user choose several zip bundle files at same time then choosing SAI,will SAI install those zip bundles at same time too?
