### ISSUE TITLE
Merge to single APK?

### ISSUE THREAD

**Issue by lyndmi** [Aefyr/SAI#21]
Can you make an option that can merge all split APK to single APK?

**Comment by Aefyr** [comment]
No, that's not the goal of SAI

**Comment by lyndmi** [comment]
Sad :(

**Comment by IRGC** [comment]
@Aefyr but can you say is it possible to merge?

**Comment by Aefyr** [comment]
It is, but it requires disassembling all splits and merging them which isn't easy to do even on Windows/Linux

**Comment by pm-pm** [comment]
Thanks for explanation. :-)
I am also looking for such a tool.
I want to pack a split apk to an one-file-apk to give it to friends and family.

**Comment by AndnixSH** [comment]
I can try to make tool only for windows but I don't have time right now

**Comment by IRGC** [comment]
Try when you are free :) you will be praised by lots of people like me😉
