### ISSUE TITLE
Failure to install, system apk update

### ISSUE THREAD

**Issue by jancm** [Aefyr/SAI#22]
Edit: just noticed you released 2.1, will try that and update this post
Edit2: 2.1 shows the same results

Pixel 3 XL
Pie, August update
Canary Magisk
Using rooted method
SAI version 2.0

Photos is now a split APK. I exported a copy using this app. Noticed that it did not include a copy of base.dm (found in Photos /data/app/ folder) so wanted to see if that would be a problem when re-installing. Went into settings and "uninstalled all updates".

Next tried to install the apks file I had just exported. Got the following error:

Rooted installer error:

 Device: google Pixel 3 XL | Not MIUI | Android 9 | Using SignerApkSource ApkSource implementation

Command: pm install-commit 824361104 
Exit code: 5
Out:
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.google.android.apps.photos signatures do not match previously installed version; ignoring!]
=============
Err:

**Comment by Aefyr** [comment]
Do you have APK signing enabled? It would explain installation error. Also I'm not sure what the dm file supposed to be, seems to be included with every system app tho, I don't think it's neccessary for app installation, probably gets created by system.

**Comment by Aefyr** [comment]
Oh, I've just noticed

> Device: google Pixel 3 XL | Not MIUI | Android 9 | Using SignerApkSource ApkSource implementation

So, yeah, disable APK signing in settings (since you can't update an app with an APK with a different signature)

**Comment by jancm** [comment]
Thanks. Disabling apk signing worked. I knew that you couldn't update apk with a different signature, but thought that since you're copying existing apk filters the signatures would match. I guess it's not quite that simple 😉

Missing dm file doesn't appear to be an issue. I restored data via Titanium and it's the same as it was before. dm file might be a profile file. At the start it has "PK<bunch of hex chars>primary.prof" and towards the end "primary.profPK"

**Comment by Aefyr** [comment]
Exported APKs always retain original signature, but you've tried to install it with signing enabled. Anyway, I'm closing the issue then
