### ISSUE TITLE
Request: split the APK parsing code to a new repository

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Aefyr/SAI#224]
There are plenty of libraries and websites to parse APK files.
However, very few can be easily used right on Android itself.
The parsing using the Android framework is also very limited, as it can't parse split APK files and also can handle only by a file path and not by InputStream.

I actually tried to help on some library that is used for parsing of APK files (created a fork [here](https://github.com/AndroidDeveloperLB/apk-parser) , trying to fix some issues in it), but sadly the repository is not maintained anymore:

https://github.com/hsiafan/apk-parser

I've noticed that this repository does some parsing of APK files:
https://github.com/Aefyr/SAI/blob/master/app/src/main/java/com/aefyr/sai/installerx/resolver/meta/impl/DefaultSplitApkSourceMetaResolver.java#L78

Can you please consider splitting this part of the repository into another?
Maybe even use the library I've mentioned and update it according to the current repository's need (but please don't remove functionality, at least not important one)?

This could revive the availability of such libraries.

**Comment by SSVUSDNHL** [comment]
> Существует множество библиотек и веб-сайтов для анализа файлов APK.
> Однако очень немногие из них можно легко использовать прямо на самом Android.
> Синтаксический анализ с использованием платформы Android также очень ограничен, так как он не может анализировать разделенные файлы APK, а также может обрабатываться только по пути к файлу, а не по входному потоку.
> 
> Я на самом деле пытался помочь в какой-то библиотеке, которая используется для анализа файлов APK (создал форк [здесь](https://github.com/AndroidDeveloperLB/apk-parser ) , пытаясь исправить некоторые проблемы в нем), но, к сожалению, хранилище больше не поддерживается:
>
> https://github.com/hsiafan/apk-parser
> 
> Я заметил, что этот репозиторий выполняет некоторый синтаксический анализ файлов APK:
> https://github.com/Aefyr/SAI/blob/master/app/src/main/java/com/aefyr/sai/installerx/resolver/meta/impl/DefaultSplitApkSourceMetaResolver.java#L78
> 
> Не могли бы вы, пожалуйста, рассмотреть возможность разделения этой части репозитория на другую?
> Может быть, даже использовать библиотеку, о которой я упоминал, и обновить ее в соответствии с потребностями текущего репозитория (но, пожалуйста, не удаляйте функциональность, по крайней мере, не важную)?
> 
> Это могло бы оживить доступность таких библиотек.
>

**Comment by AndroidDeveloperLB** [comment]
Why close?
