### ISSUE TITLE
[Feature request] Same theme and icon for F-Droid

### ISSUE THREAD

**Issue by julianfairfax** [Aefyr/SAI#225]
Hi,
First off, thanks for making this app. It's very useful to install apps that use Google's dumb new format. Since I value my privacy, I installed it through F-Droid. At first glance it looked the same, but when I actually got the app installed, I discovered it had a different theme and icon than usual. If possible, I think it would be better to use the same theme and icon for the F-Droid version, and I don't see why this isn't done now. Thanks again for this app!

**Comment by the4anoni** [comment]
You can change theme in settings...

**Comment by julianfairfax** [comment]
But not the icon

**Comment by the4anoni** [comment]
> But not the icon

This may be fixed via this https://github.com/Aefyr/SAI/issues/231
