### ISSUE TITLE
INSTALL_PARSE_FAILED_NO_CERTIFICATES when installing apk on Android 11

### ISSUE THREAD

**Issue by mrugtangy** [Aefyr/SAI#237]
I'm trying to install an apk with 'Sign APKs' turned on but it fails to install with this error :

INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package com.samsung.android.game.gamehome

**Comment by singhalrishi27** [comment]
@tangymc this repo is no longer maintained
