### ISSUE TITLE
Open with defined file manager app

### ISSUE THREAD

**Issue by lyndmi** [Aefyr/SAI#24]
Is there a way to open with my defined file manager app like X-plore to select apks to install?
I like X-plore better because I can select my files directly on my network drive for quick testing

**Comment by Aefyr** [comment]
There are two problems when using an external app to pick files - filtering by multiple file types (Technically there's a feature for that but it only works in the default Documents app out of the apps I tried which included X-plore and Solid Explorer) and that filtering only works by MIME types, so there's no way to filter .apks files.

That being said, you can just put a .apks file on your network drive and open it with SAI from X-plore.

**Comment by lyndmi** [comment]
Oh ok
I tried to open apks with other program but SAI is not listed
Possible to make .apks recognizeable with SAI in system wide?

**Comment by Aefyr** [comment]
It should be recognizable system-wide, it for sure works properly with Solid Explorer and Total Commander. In X-plore there's that weird open as dialog, but if you pick "\*/\*", SAI is listed there. 
However there might be a problem if your .apks file contains more than five dots total in it's path, if that's the case, most apps actually won't recognize it as openable in SAI.

**Comment by Aefyr** [comment]
Old
