### ISSUE TITLE
ability to backup non split apk as .apk not .apks

### ISSUE THREAD

**Issue by sobaee** [Aefyr/SAI#242]
Hello dear developer

We need to be able to backup non split apps as .apk

Currently the app backup any app as .apks even those non split apps

Please fix it

**Comment by VasilisKos** [comment]
That option is already available. There's a relevant toggle switch in the pop up window when selecting to backup an non-split app.

**Comment by sobaee** [comment]
I need it to be done automatically, and to be supported by SAI as backup

Because when I toggle "export as .apk file" I see this message:
(Export a single selected part as a .apk file. Exported .apk files are not backups and won't be managed by SAI)
And then I can't see that app is backed up on apps list like split apps

I need SAI be general backup up app for split and non split apps (all to be managed by SAI )

See this picture:
![Screenshot_20220507215618](https://user-images.githubusercontent.com/65910585/167268875-f9c4aee2-d852-4aa7-82f6-a906f7920b0d.jpg)

In this picture I did backup for "Lens apk" app by the way that you have said but I can't see the icon of backed up app beside it
