### ISSUE TITLE
Backup file names issue

### ISSUE THREAD

**Issue by VasilisKos** [Aefyr/SAI#244]
The backuped app version number in the backup file names is split by commas, instead of dots like it's supposed according to the preview in the backup settings. e.g. SAI_4,5.apk instead of SAI_4.5.apk.
Maybe it has to do with the Greek language my Android is set to? (We use , instead of . for decimals)
It's a minor issue, but maybe it can be fixed in some future update.

**Comment by vomw** [comment]
https://github.com/Aefyr/SAI/issues/85#issuecomment-595236867
