### ISSUE TITLE
Request: Batch export

### ISSUE THREAD

**Issue by jancm** [Aefyr/SAI#25]
It would be nice to be able to select multiple (or all) found split APKs for export.

Right now I'm getting ready to do a clean install moving to Q and am exporting all the split apps, since Titanium doesn't handle them correctly (I can still use Titanium for data restores though).

It would have been helpful to easily export all the APKs instead of individually clicking through 35 entries.

**Comment by Aefyr** [comment]
Added in 2.3

**Comment by jancm** [comment]
Thanks. So in the process of moving to Q I also discovered that you can't
batch install apks files. I wonder if it would be possible to add that?
Obviously mixing apk files with apks files won't work but if only apks
files are selected can't you serially install multiples?

Last request - can you have a default folder (like the SAI folder) that the
install always opens in?

Thanks again. This program is filling a need that I suspect a lot of people
don't even (yet) realize is there. It works, and works well - just needs
some UI stuff ironed out (IMHO).

**Comment by Aefyr** [comment]
> Thanks. So in the process of moving to Q I also discovered that you can't batch install apks files. I wonder if it would be possible to add that?

The current UI architecture is designed for a single ongoing installation, so, no, at least for now

> Last request - can you have a default folder (like the SAI folder) that the install always opens in?

You can already do that, there is an option in settings called "Home directory"
