### ISSUE TITLE
Request: app version 

### ISSUE THREAD

**Issue by jancm** [Aefyr/SAI#26]
Include the app version as part of the APKs name. It looks like the current name is created based on epoch time, but no indication of the app version.

**Comment by Aefyr** [comment]
Made a new format in [this](https://github.com/Aefyr/SAI/commit/0e12783f5743d1cb4148d65888983e960aa4c748) and [this](https://github.com/Aefyr/SAI/commit/bcc46c110e110ed553e46acaed07c9f6c6331d12) commits - PACKAGE-VERSION-TIMESTAMP.apks, though all dots in package and version are replaced with commas to avoid the problem with having more than 5 dots in .apks file path.
