### ISSUE TITLE
Help with memory 

### ISSUE THREAD

**Issue by leopeo-star** [Aefyr/SAI#265]
Can someone help me i tried to install a game apk with sai split installer the size of the apk is 3.8gb soo prior to this i had 5gb left i started installing it but i closed it by mistake and somehow i lost space in my storage like now i have 1gb storage left but the apk isn't installed i ecen uninstalled the sai app but still did not recover the lost storage in my internal memory storage in my mobile i tried looking in app/data i can't find any file that the app may have created but none (there was a message displayed before installing that 3.8gb game that the apk is larger then 150 gb in case of error u may not be able to reclaim lost space or something without root what does it mean i have no idea like do i permanently loose storage of my phone bcz of it

**Comment by esulumo** [comment]
i have the same prob and i don't know what to do
