### ISSUE TITLE
INSTALL_FAILED_ABORTED

### ISSUE THREAD

**Issue by THZthz** [Aefyr/SAI#274]
Got "INSTALL_FAILED_ABORTED: User rejected permissions" when installing ".apks" on Android12.

How to solve this?

**Comment by Tombstone2K** [comment]
A lot of people seem to be having this issue. 
Found a thread on reddit about the same -> https://old.reddit.com/r/androidapps/comments/14qjshk/how_to_install_split_apks_apks_on_android12/

Any thoughts ?  @Aefyr
