### ISSUE TITLE
SAI installer recognised from within Chrome Downloads

### ISSUE THREAD

**Issue by beecho01** [Aefyr/SAI#285]
When an *.apkm is downloaded from Chrome and the "File downloaded" toast appears at the top of the viewport, and "Open" is selected within this toast, no installer is recognised. The same file, when selected from the "Internal file picker" is recognised, opened and installed without issue. Examples or screenshots can be provided if this is needed and undesired behaviour.

**Comment by vaimalaviya1233** [comment]
technically it should be showing that as filetype is included in manifest https://github.com/Aefyr/SAI/blob/55505d231b1390e824d1cc0c8f4fa35fd4677105/app/src/main/AndroidManifest.xml#L167
