### ISSUE TITLE
Split APK Black Screen

### ISSUE THREAD

**Issue by MrCWei** [Aefyr/SAI#33]
My phone :
1.first device:
MEIZU PRO 6 Plus with Flyme 7.3.0.0A
bootloader locked, so no root
GAPPS preinstall but no google account
google app disabled on settings

2.second device:

vivo IQOO with Funtouch Os 9
bootloader locked, so no root
GAPPS preinstall but no google account
google app disabled on settings

app link :https://play.google.com/store/apps/details?id=com.playkot.ageofmagic

**Comment by Aefyr** [comment]
If the black screen is within the app, I don't think that's an issue with SAI

**Comment by MrCWei** [comment]
> If the black screen is within the app, I don't think that's an issue with SAI

But I've tested the same app with GooglePlay and everything works.

**Comment by Aefyr** [comment]
Abandoned and likely not an issue with SAI itself
