### ISSUE TITLE
Rootless 

### ISSUE THREAD

**Issue by dickyharper** [Aefyr/SAI#34]
My device does not support split app. But Google Play can load them. Maybe I can work to Sai with the ADB? No way there is a  without root? Sorry for my English.

**Comment by Aefyr** [comment]
You mean your devices runs Android version lower than 5.0? If so, Google Play will just download merged APKs. Split APKs just weren't a thing before 5.0, so root won't help you there.

**Comment by dickyharper** [comment]
My device is Android 5.0.1.  But I can't back up the app because I can't install Split apks.  If Root works, I get root privilege on the device.  But I'il wait if SAI works n the future.

**Comment by Aefyr** [comment]
So, you get an error when installing split APKs? Can you provide the error text and your device model and ROM?

**Comment by dickyharper** [comment]
Your ROM is incompatible with rootless installer. Try enabling rooted installer in SAI settings if you have root

Samsung s4 GT-I9500
Android: 5.0.1
LRX2CC.I9500XXUHPJ3

**Comment by Aefyr** [comment]
Well, yeah, I can't see any other solution apart from using root. I've added support for Shizuku in latest commits, but it only works on Android 6.0+

**Comment by Aefyr** [comment]
Actually you can just use ADB directly to install that app

**Comment by dickyharper** [comment]
I understand. I'll try the Adb method.  Thanks. :)

**Comment by dickyharper** [comment]
One last question.  Is it possible to reassemble these apk's using apktool?

**Comment by Aefyr** [comment]
You mean merge? It must be possible, but it's gonna be really hard to merge resources manually, maybe there's an existing tool for that, but idk

**Comment by dickyharper** [comment]
Yeah.  Even if it's hard, I'd want to try.  I know the app I can do on the phone, but I need some more information.  I'm sorry I wasted your time.  Thanks for the answers.
