### ISSUE TITLE
Error "App not installed / Installation failed" on Redmi Note 6 Pro non-rooted

### ISSUE THREAD

**Issue by yop37** [Aefyr/SAI#4]
Hi,
I always this error when i want to install split apks (multiple-apks, zip archive, apks file) on my device : Xiaomi Redmi Note 6 Pro "non-rooted"
The permissions "Storage" and "unknown sources" are enabled in the application manager, and "MIUI optimization" is disabled for this app.

versions tested : 1.15, 1.16, 1.17, 1.18, 1.19.

![SAI-AppNotInstalled](https://user-images.githubusercontent.com/30030549/56502599-2d482e80-6513-11e9-9a18-2033703c2643.png)

Is it possible to merge split-apks on Windows?

**Comment by Kill-A-Bytes** [comment]
i am also getting the same error in redmi note 7

**Comment by yop37** [comment]
> 
> 
> i am also getting the same error in redmi note 7

On all versions of SAI?

**Comment by raulmesa** [comment]
i am also getting the same error in redmi note 5 with version sai 1.9

**Comment by Aefyr** [comment]
Happens on some MIUI versions, system just rejects the APKs as if they have broken/conflicting signatures. Sometimes this can be fixed by disabling MIUI optimizations in developer options. Though I suggest you install some decent AOSP-based ROM.

**Comment by raulmesa** [comment]
> Happens on some MIUI versions, system just rejects the APKs as if they have broken/conflicting signatures. Sometimes this can be fixed by disabling MIUI optimizations in developer options. Though I suggest you install some decent AOSP-based ROM.

Thanks..!!! working for me, disabling MIUI optimizations....
