### ISSUE TITLE
How to Export Split Apks with minimum Architecture support?

### ISSUE THREAD

**Issue by congloi** [Aefyr/SAI#41]
Hi, It's not a bug, but I don't know where to ask.

I use Redmi Note 7 (64 bit support). 

When I export Split Apks with SAI, default is base.apk with config.arm64-v8a.apk.

I want export with lower architecture support, ie: config.armeabi-v7a.apk.

How can do that or It's impossible?

Thanks so much

**Comment by Aefyr** [comment]
You need a device that runs a ARMv7 CPU for Google Play to download 32-bit libs (why would you need them if you have a 64-bit device though?), you can probably use an emulator for that, but ARM emulators are really laggy.

**Comment by congloi** [comment]
Thanks Aefyr, some time I need backup app for older phone.

btw, in next version, can you add "sort" function on Export windows, Version 2.5 only sort by name default, thanks very much

**Comment by Aefyr** [comment]
> btw, in next version, can you add "sort" function on Export windows

Probably, but I'm not sure when
