### ISSUE TITLE
Please allow home directory outside internal storage

### ISSUE THREAD

**Issue by johanw666** [Aefyr/SAI#48]
The current directory picker to select the home directory starts in the internal storage, and manual editing the directory is also not possible. So it is currently not possible to select a directory on the removable storage or deeper, not even when you are root and have disabled artificial restrictions on the use of a memory card.

Would it be possible to remove this restriction? I download my apk's to removable storage but now I have to copy the split ones to internal memory first to install them.

**Comment by Aefyr** [comment]
If you want to install apps from a removable storage, either open it with SAI if it's a .apks file or long click the install button to select files with system file picker which has access to removable storage. SAI's current internal file picker library doesn't support browsing files outside internal storage.
