### ISSUE TITLE
Miui 11 - Android 10

### ISSUE THREAD

**Issue by KashaMalaga** [Aefyr/SAI#49]
[log2.txt](https://github.com/Aefyr/SAI/files/3776350/log2.txt)
Hello,
After a few tries isnt working. Already tried all flags from develop screen, having said that, now in Miui 11 there is no "MIUI Optimization" anymore :(

Attached log, ofc seems API mod issues...

**Comment by Aefyr** [comment]
I don't think you can do anything other than using another installer type or switching to a decent ROM

**Comment by KashaMalaga** [comment]
Thanks for the fast answer. That's...the thing you are totally right, so messy the API....
Anyway tried with shizuku by adb and all kinds permissions but still start.sh permission denied, chmod done etc..

**Comment by Aefyr** [comment]
What? Were you unable to start Shizuku or was SAI still unable to install apps even with Shizuku?

**Comment by KashaMalaga** [comment]
A)

**Comment by Aefyr** [comment]
Maybe Shizuku doesn't support Q yet
