### ISSUE TITLE
Language setting error

### ISSUE THREAD

**Issue by hsh93** [Aefyr/SAI#5]
The Apps(Rosetta Stone and Runtastic Results) I used before ran in Chinese，they automatically change to English after updated with SAI. No matter I use any versions of SAI or clear the data of Apps or reinstall them, they still cannot run in my system language Chinese. Even parts of Runtastic Results's functions display in both Chinese and English, that bothers me.

I need help

thx

![11556441263_ pic](https://user-images.githubusercontent.com/50070675/56861657-70077c00-69d5-11e9-92ea-8b97793e8ee3.jpg)

**Comment by Aefyr** [comment]
Chinese localization probably comes as a separate split apk part and you haven't installed it

**Comment by madbulldog** [comment]
Dutch language is not complete. In Trivia crack and runtastic. It's half english, half dutch. It's annoying. Can you please fix this in an update, like you did with chinese.

Regards, mad bulldog

**Comment by Aefyr** [comment]
> Dutch language is not complete. In Trivia crack and runtastic. It's half english, half dutch. It's annoying. Can you please fix this in an update, like you did with chinese.

That update added chinese translation to SAI itself, lol. As I've answered above, dutch translation most likely comes as a separate apk and you haven't installed it alongside base apk.

**Comment by madbulldog** [comment]
There is no alongside base apk. Just one apk 41.3 mb in size. I downloded it from a2zapk.com. after instalation the main programme is in english, but the question are in dutch ( using trivia crack ). The language settings are in dutch. The same with runtastic and other programmes. The main programme is english after install. Before the sai option, it was an apk, 52.5 mb. After installation it was complet dutch.
So it has to do with sai, that some alongside base files are not installed.

Regards, mad bulldog

**Comment by madbulldog** [comment]
Sorry, ot"s a zip file containing 3 files: com.etermax.preguntados.pro-373.apk, config.hdpi-373.apk and config.pl-373.apk.
Am i missing files for the complete dutch install?
Regards, mad bulldog

**Comment by Aefyr** [comment]
> Am i missing files for the complete dutch install?

Yeah, judging by names, those are base apk (with just one language, most likely english), graphics for hdpi screens apk and polish localization apk. You'll need dutch localization apk for the app to be in dutch.

**Comment by madbulldog** [comment]
Oké, thanks for the reply. That seems to be the problem. The one who cracked it and used sai to split the files. Left out all other languages. It's a bomber, but i will have to life with it, i gess.
Regards, mad bulldog
