### ISSUE TITLE
Replace comma , sympol with dots

### ISSUE THREAD

**Issue by Qyrln** [Aefyr/SAI#53]
Hello , Dev
Firstly ,thanks for your great app
Secondly and please replace comma sympol with dots ( . ) in the exported app name format 
Or at least make and option for it . because I don't like comma sympol in app names :'(

**Comment by Aefyr** [comment]
Dots are replaced because if there are more than 5 dots total in the whole path to an .apks file, you won't be able to open it with SAI. You can disable this behavior in the super secret settings (3 or more taps an then a long tap on the SAI logo on about screen)

**Comment by Qyrln** [comment]
it with dots now , Opening it with sai isn't a problem for me .
Thanks ,Dev
