### ISSUE TITLE
no sai apk installation doesn't work with root

### ISSUE THREAD

**Issue by janilde16** [Aefyr/SAI#56]
every time i try to install apk doesn't work and give error

Rooted installer error:

 Device: lge LG-M250 | Not MIUI | Android 7.0 | Using DefaultApkSource ApkSource implementation | SAI 3.0

Command: pm install-commit 1029042391
Exit code: 7
Out:

=============
Err:
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
![Screenshot_2019-11-24-13-42-30](https://user-images.githubusercontent.com/58144062/69497869-532a1d00-0ec0-11ea-83ea-c21094543d78.png)

**Comment by Aefyr** [comment]
This error means you haven't selected an APK with native libs for your CPU architecture

**Comment by janilde16** [comment]
and have a way to solve?

**Comment by Aefyr** [comment]
Well, you need APKs for your CPU architecture.
Anyway, closing the issue, because it has nothing to do with SAI itself.

**Comment by janilde16** [comment]
Ok thank you!
