### ISSUE TITLE
Any plans to bring the app to Android TV?

### ISSUE THREAD

**Issue by dwm1909** [Aefyr/SAI#57]
Would be great if this app was build for Android TV as well.

**Comment by codev01** [comment]
А для чего?
for what?

**Comment by Aefyr** [comment]
It works on Android TV emulator, what's exactly your issue?

**Comment by dwm1909** [comment]
Have not try sideload it i was thinking mabye actived it to show up on the Play Store. 
But going to try sideload it then and try :)

**Comment by Aefyr** [comment]
If it's convenient enough to use with a remote, I'll make it supported on GP and fix icon, is it though?

**Comment by dwm1909** [comment]
Works flawless on the remote controll on my TCL Android TV :) so yehe would be great if man cold downloads it from GP as well just sidad load it and icon would make it alot faster to open.

**Comment by Aefyr** [comment]
Ok, support added in https://github.com/Aefyr/SAI/commit/7b9b80286973ff6889f3903b68f952a6f689d0b1. Also I've found out that D-pad doesn't work with my single choice bottomsheet and I couldn't get it to work, hopefully all remotes have a joystick for mouse emulation

**Comment by Aefyr** [comment]
> can you add a map with files for translate the app to Swedish as well

What do you mean by that?

**Comment by dwm1909** [comment]
> Ok, support added in [7b9b802](https://github.com/Aefyr/SAI/commit/7b9b80286973ff6889f3903b68f952a6f689d0b1). Also I've found out that D-pad doesn't work with my single choice bottomsheet and I couldn't get it to work, hopefully all remotes have a joystick for mouse emulation

Have not try the map navigation with my SteelSeries Stratus Duo gamepad just used my TCL RC602S remote, and that was wroing to navigate to left right down and up everything i need to navigate true the map. 

yes like a map with se-SV more language support cold translate english to swedish.

**Comment by Aefyr** [comment]
I dunno, I don't really wanna add any workarounds for D-pad and I'm not sure why I was unable to focus views even though they had all of the necessary attributes. Anyway, as for the swedish translation, I don't get why can't you just create strings.xml and arrays.xml with swedish modifier

**Comment by Aefyr** [comment]
Added in 3.1
