### ISSUE TITLE
Upload to APKMirror

### ISSUE THREAD

**Issue by NatoBoram** [Aefyr/SAI#59]
Hi!

Would it be possible to add a feature to upload non-splits to APKMirror? Once they figure out how they want to receive splits, it would be nice to be able to upload them from the app.

Have a nice day!

**Comment by Aefyr** [comment]
What does this have to do with SAI tho? It's not a APKMirror client

**Comment by NatoBoram** [comment]
I saw it more as a way to manage APKs, and one cool feature of managing APKs is to share those APKs. It's okay if you don't see a point to it, I was just browsing for APK managers that would allow me to batch upload APKs for region-locked, vendor-locked or GApps-less people to enjoy these.

**Comment by NatoBoram** [comment]
> I don't wanna support APKMirror with their DRM and tons of ads.
