### ISSUE TITLE
Files translation

### ISSUE THREAD

**Issue by jekovcar** [Aefyr/SAI#64]
Update bulgarian translation for SAI v3.3
[values-bg.zip](https://github.com/Aefyr/SAI/files/4143899/values-bg.zip)

**Comment by Aefyr** [comment]
Thanks, I've added arrays.xml, but strings.xml was the same as you've sent before. Also please consider using a pull request next time

**Comment by jekovcar** [comment]
I would love to, but stupidly I can’t create a pull request every time. strings.xml above is not that as i've sent before for v3.2. Anyway, now send it with corrected tags suiteable to the english strings.
[values-bg.zip](https://github.com/Aefyr/SAI/files/4144187/values-bg.zip)
