### ISSUE TITLE
Translations on crowdin?

### ISSUE THREAD

**Issue by the4anoni** [Aefyr/SAI#66]
Hello
What about translations on crowdin?
It is free for open projects.
Translating via notepad++ is pain for me...
I want to translate app to Polish.

**Comment by Aefyr** [comment]
Is Android Studio's translations editor not an option for you?

**Comment by the4anoni** [comment]
I am not programmer, never had to use Android Studio for translations.

Crowdin is very convenient to translate apps.

**Comment by Aefyr** [comment]
Ok, I've created a project for SAI and submitted an opensource application. Crowdin UX is very confusing though, some translated strings show up as non-translated even though they appear in downloaded translation files and I have no idea how to enter proofreading mode. Anyway, waiting for application response

**Comment by Aefyr** [comment]
Yay, they've accepted the application. Now waiting for support response about proofreading and bugged strings

**Comment by Aefyr** [comment]
Support helped, I think I've finally set it up properly - https://polychromaticfox.crowdin.com/split-apks-installer

**Comment by uDEV2019** [comment]
Because not all translated strings got incorporated (merged) to crowdin, i've corrected/added them for the german translation.

**Comment by the4anoni** [comment]
@Aefyr I've translated much part of Sai before you moved to crowdin enterprice.
Can you move Polish translation to new crowdin?

**Comment by Aefyr** [comment]
@uDEV2019 I don't see any unapproved words in german translation.

@the4anoni There's "Upload Tranlations" button in File menu.

**Comment by Aefyr** [comment]
Oh, I got it, you were talking about non-enterprise Crowdin, I haven't even set it up properly

**Comment by Aefyr** [comment]
> @the4anoni There's "Upload Translations" button in File menu.

Actually I can't find a way to upload XLIFF translations and exported XML are a incosistent with double quotes with preceding backslashes (That should be fixed soon). I'll ask support about XLIFF

**Comment by Aefyr** [comment]
Ok, they helped, I imported Polish translation

**Comment by uDEV2019** [comment]
> Oh, I got it, you were talking about non-enterprise Crowdin, I haven't even set it up properly

Yup, i used the non-enterprise variant.

**Comment by Aefyr** [comment]
Ok, issues with exported translations have been fixed, so now I can properly use Crowdin
