### ISSUE TITLE
[feature request] show file size

### ISSUE THREAD

**Issue by IRGC** [Aefyr/SAI#70]
can you show file size in the file explorer?
like Last Edited: datetime, Size: 9.24MB
also have file sorting based on size in settings?
![image](https://user-images.githubusercontent.com/36361542/74341271-6cf74400-4dcd-11ea-9bbf-f7ca35680d1b.png)

**Comment by Aefyr** [comment]
Ok, I've modified half-dead filepicker lib that SAI uses

**Comment by IRGC** [comment]
thanks bro
