### ISSUE TITLE
Signature problem.

### ISSUE THREAD

**Issue by master1274** [Aefyr/SAI#8]
https://drive.google.com/folderview?id=1-WOh4lfkYcQKo8aTLtQKystoPmiVRzET

![Screenshot_20190504-225559](https://user-images.githubusercontent.com/20639709/57184190-5926c500-6ec0-11e9-94a1-1bd613872b94.png)

**Comment by Aefyr** [comment]
Disable APK signing in SAI. Some apps have extractNativeLibs flag set to false in their manifest, which requires native libs stored in an APK file to be uncompressed and page aligned, but SAI's signer doesn't support that.

**Comment by Aefyr** [comment]
zipaling support was added in https://github.com/Aefyr/SAI/commit/2c1c0a582399533ee3e4f23adf565710e49a53c0
