### ISSUE TITLE
Fdroid build

### ISSUE THREAD

**Issue by Qyrln** [Aefyr/SAI#81]
Hello , Dev 
Thangs for this great app ,but the last update on fdroid v2.4 , so won't you update the fdroid build to latest one like PS and github ?

**Comment by Aefyr** [comment]
F-Droid's bot builds apps for their repository, but it's failing to build SAI. Previously it was due to Shizuku dependency being in a custom repo, [but now it can't parse build.gradle for some reason](https://f-droid.org/wiki/page/com.aefyr.sai.fdroid/lastbuild). Someone [made an issue](https://gitlab.com/fdroid/fdroiddata/issues/1840) to resolve that, but it's been kinda abandoned.

**Comment by licaon-kter** [comment]
As the issue there says, are those libs unavailable in [a trusted repo](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L99) or can't be build before building the app?

**Comment by Aefyr** [comment]
Yeah, Shizuku's license only appears in [publish.gradle](https://github.com/RikkaApps/Shizuku/blob/675c7f31864746fe208217c0d62f8d272f9fcef2/publish.gradle#L6) indeed. Thanks for [opening an issue](https://github.com/RikkaApps/Shizuku/issues/56) in their repo

**Comment by licaon-kter** [comment]
FYI https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6556

**Comment by Aefyr** [comment]
Thanks, I've removed custom repo and updated Shizuku API dependency in https://github.com/Aefyr/SAI/commit/375e5d4f4f56ecefad36344f66780868f7b8e0e2

**Comment by TPS** [comment]
Just to confirm, is [the Shizuku license resolved satisfactorily](https://github.com/RikkaApps/Shizuku/issues/56#issuecomment-1826415470) enough for F-droid being ok w/ SAI's legality?

**Comment by TPS** [comment]
I guess so, as [v3.9 hit main F-Droid repo on 3-31](https://f-droid.org/en/packages/com.aefyr.sai.fdroid/)!

**Comment by licaon-kter** [comment]
@TPS legality? Do tell more

**Comment by Aefyr** [comment]
> I guess so, as [v3.9 hit main F-Droid repo on 3-31](https://f-droid.org/en/packages/com.aefyr.sai.fdroid/)!

Oh, I didn't notice, guess this issue is resolved then
