### ISSUE TITLE
Add: Change App language

### ISSUE THREAD

**Issue by ghost** [Aefyr/SAI#82]
## Description

It would be very good if the app language could be changed without changing the system language.

## App info

- SAI 3.7
https://github.com/Aefyr/SAI/releases/tag/3.7

**Comment by Aefyr** [comment]
Why would you need that though?

**Comment by USB3-2-10Gbit** [comment]
When users come from different countries but prefer the English language for some apps without changing the system language.

**Comment by megapro17** [comment]
This is useless option, if you want to change app language change it globally. I'm against it

**Comment by Aefyr** [comment]
Yeah, I kind agree with you, @megapro17, but then again, I also do prefer some apps in English which isn't my system language (SAI is used for like a minute at a time by most people though).
Anyway, I'll look into ways to implement it after I'm done with auto theme switching (I mean obviously it should be via configuration override in context or it's not viable, but I'm concerned about stuff from libs). If there's a nice way to implement it properly, I'll probably do that
