### ISSUE TITLE
Add: Clear the installation history

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [Aefyr/SAI#83]
## Description

In the "Installer" section, there is no way to select one, several or all of the entries to clear the installation history.

## App info

- SAI 3.7
https://github.com/Aefyr/SAI/releases/tag/3.7

**Comment by Aefyr** [comment]
Why would you need that though?

**Comment by USB3-2-10Gbit** [comment]
Sometimes I have deleted a few apps and it is then confusing if in the "Installer" section can still see the outdated entries or there was an error during the installation.

**Comment by Aefyr** [comment]
I don't get what is confusing. Anyway, I don't think it's possible with the current architecture, so won't be implemented at least for now.

**Comment by USB3-2-10Gbit** [comment]
Or for a better overview.
