### ISSUE TITLE
Add: Several selection function for Export

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [Aefyr/SAI#84]
## Description

In the "Export" section, there is no way to select several or all entries to export the APK file. For split APK only several selection function is missing.

## App info

- SAI 3.7
https://github.com/Aefyr/SAI/releases/tag/3.7

**Comment by Aefyr** [comment]
Makes sense, I'll see if I can integrate it there properly

**Comment by Aefyr** [comment]
Implemented in https://github.com/Aefyr/SAI/commit/a376df736b6e273119f0554db645d76d84c5a38a
