### ISSUE TITLE
Add: Select comma or dot for file name

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [Aefyr/SAI#85]
## Description

Currently, when exporting an APK file, this file name is displayed in the File Manager app (with commas).

`NewPipe_0,18,5_(850)_org,shabi,newpipe_1583414036.apk`

In the "Settings" there should also be the possibility to select the dot for the file name. This is how it would look like.

`NewPipe_0.18.5_(850)_org.shabi.newpipe_1583414036.apk`

## App info

- SAI 3.7
https://github.com/Aefyr/SAI/releases/tag/3.7

**Comment by Aefyr** [comment]
That is possible in debug settings (3+ taps and then a long tap on SAI logo on about screen). But I want add that to main settings since commas are used for compatibility with "open with" feature - 5 ore more dots in path to an .apks file break it.
