### ISSUE TITLE
INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113

### ISSUE THREAD

**Issue by sww0825521xy** [Aefyr/SAI#91]
use adb install-multiple command to install split apk failed, also use SAI to install failed.
Any solution? 
adb install-multiple base.apk split_config.arm64_v8a.apk split_config.en.apk split_config.xxhdpi.apk split_config.zh.apk split_df_fusing.apk
adb: failed to finalize session
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by IRGC** [comment]
may be your device supports only armeabi-v7a but you are trying to install arm64-v8a ?

**Comment by Aefyr** [comment]
@IRGC is right, there are no libs for your device architecture in the APKs you're trying to install.
