### ISSUE TITLE
Automatic white/dark theme

### ISSUE THREAD

**Issue by Oizaro** [Aefyr/SAI#96]
Hi.

It can be possible to add another theme "based on system"? In this way there will be no need to change the theme every time.

Thanks.

**Comment by Aefyr** [comment]
So like you enable some kind of auto theme and then select a light theme and a dark theme for it?

**Comment by Oizaro** [comment]
@Aefyr

Exactly.

**Comment by megapro17** [comment]
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme
